
-- Name: audit_current_user_id(); Type: FUNCTION; Schema: public; Owner: -

CREATE FUNCTION public.audit_current_user_id() RETURNS integer
    LANGUAGE plpgsql
    AS $$
DECLARE
    raw_value text;
BEGIN
    raw_value := current_setting('app.current_user_id', true);

    IF raw_value IS NULL OR BTRIM(raw_value) = '' THEN
        RETURN NULL;
    END IF;

    RETURN raw_value::integer;
EXCEPTION
    WHEN OTHERS THEN
        RETURN NULL;
END;
$$;


-- Name: set_update_metadata(); Type: FUNCTION; Schema: public; Owner: -

CREATE FUNCTION public.set_update_metadata() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.date_update = NOW();

    IF current_setting('app.current_user_id', true) IS NOT NULL
        AND current_setting('app.current_user_id', true) <> ''
    THEN
        NEW.user_update = current_setting('app.current_user_id', true)::integer;
    END IF;

    RETURN NEW;
END;
$$;


-- Name: write_crud_audit(); Type: FUNCTION; Schema: public; Owner: -

CREATE FUNCTION public.write_crud_audit() RETURNS trigger
    LANGUAGE plpgsql
    AS $_$
DECLARE
    source_row jsonb;
    record_pk jsonb := '{}'::jsonb;
    pk_name text;
    changed_by_user_id integer;
BEGIN
    source_row := CASE
        WHEN TG_OP = 'DELETE' THEN to_jsonb(OLD)
        ELSE to_jsonb(NEW)
    END;

    changed_by_user_id := public.audit_current_user_id();

    FOREACH pk_name IN ARRAY TG_ARGV LOOP
        record_pk := record_pk || jsonb_build_object(pk_name, source_row -> pk_name);
    END LOOP;

    EXECUTE format(
        'INSERT INTO public.%I_l (operation, changed_at, changed_by_user_id, record_pk, row_data)
         VALUES ($1, NOW(), $2, $3, $4)',
        TG_TABLE_NAME
    )
    USING TG_OP, changed_by_user_id, record_pk, source_row;

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;

    RETURN NEW;
END;
$_$;


-- Name: write_survey_auto_creation_config_audit(); Type: FUNCTION; Schema: public; Owner: -

CREATE FUNCTION public.write_survey_auto_creation_config_audit() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
    changed_by integer;
    audit_record_pk jsonb;
    audit_row_data jsonb;
BEGIN
    IF current_setting('app.current_user_id', true) IS NOT NULL
        AND current_setting('app.current_user_id', true) <> ''
    THEN
        changed_by := current_setting('app.current_user_id', true)::integer;
    END IF;

    IF TG_OP = 'DELETE' THEN
        audit_record_pk := jsonb_build_object('id_config', OLD.id_config, 'id_survey', OLD.id_survey);
        audit_row_data := to_jsonb(OLD);
    ELSE
        audit_record_pk := jsonb_build_object('id_config', NEW.id_config, 'id_survey', NEW.id_survey);
        audit_row_data := to_jsonb(NEW);
    END IF;

    INSERT INTO public.survey_auto_creation_config_l
    (
        operation,
        changed_by_user_id,
        record_pk,
        row_data
    )
    VALUES
    (
        TG_OP,
        changed_by,
        audit_record_pk,
        audit_row_data
    );

    RETURN COALESCE(NEW, OLD);
END;
$$;




-- Name: answer; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.answer (
    id_answer integer NOT NULL,
    csp text,
    completion_date timestamp without time zone,
    id_organization_survey integer NOT NULL
);


-- Name: answer_id_answer_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.answer ALTER COLUMN id_answer ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.answer_id_answer_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- Name: answer_item; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.answer_item (
    id_item integer CONSTRAINT history_answer_item_id_item_not_null NOT NULL,
    id_answer integer CONSTRAINT history_answer_item_id_answer_not_null NOT NULL,
    question_order integer CONSTRAINT history_answer_item_question_order_not_null NOT NULL,
    question_text text CONSTRAINT history_answer_item_question_text_not_null NOT NULL,
    rating integer,
    comment text,
    CONSTRAINT chk_history_answer_item_rating CHECK (((rating IS NULL) OR ((rating >= 1) AND (rating <= 5))))
);


-- Name: answer_item_id_item_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.answer_item ALTER COLUMN id_item ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.answer_item_id_item_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- Name: answer_l; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.answer_l (
    id_audit bigint NOT NULL,
    operation text NOT NULL,
    changed_at timestamp without time zone DEFAULT now() NOT NULL,
    changed_by_user_id integer,
    record_pk jsonb NOT NULL,
    row_data jsonb NOT NULL
);


-- Name: answer_l_id_audit_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.answer_l ALTER COLUMN id_audit ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.answer_l_id_audit_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- Name: app_user; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.app_user (
    id_user integer NOT NULL,
    id_organization integer,
    login text NOT NULL,
    full_name text NOT NULL,
    role text NOT NULL,
    password text NOT NULL,
    email text,
    key_csp text,
    date_begin date DEFAULT now(),
    date_end date,
    CONSTRAINT chk_app_user_role CHECK ((role = ANY (ARRAY['admin'::text, 'user'::text])))
);


-- Name: app_user_id_user_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.app_user ALTER COLUMN id_user ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_user_id_user_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- Name: app_user_l; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.app_user_l (
    id_audit bigint NOT NULL,
    operation text NOT NULL,
    changed_at timestamp without time zone DEFAULT now() NOT NULL,
    changed_by_user_id integer,
    record_pk jsonb NOT NULL,
    row_data jsonb NOT NULL
);


-- Name: app_user_l_id_audit_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.app_user_l ALTER COLUMN id_audit ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_user_l_id_audit_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- Name: auto_creation_config; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.auto_creation_config (
    id_config integer NOT NULL,
    id_creation_day integer NOT NULL,
    id_begin_day integer NOT NULL,
    working_period integer DEFAULT 8 NOT NULL,
    is_enabled boolean DEFAULT false NOT NULL,
    CONSTRAINT ck_auto_creation_config_working_period CHECK ((working_period > 0))
);


-- Name: email_config; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.email_config (
    id_config integer CONSTRAINT email_template_id_email_template_not_null NOT NULL,
    recipient_emails text DEFAULT ''::text CONSTRAINT email_template_recipient_emails_not_null NOT NULL,
    subject_text text DEFAULT ''::text CONSTRAINT email_template_subject_text_not_null NOT NULL,
    body_text text DEFAULT ''::text CONSTRAINT email_template_body_text_not_null NOT NULL,
    smtp_host text DEFAULT ''::text CONSTRAINT email_template_smtp_host_not_null NOT NULL,
    smtp_port integer DEFAULT 587 CONSTRAINT email_template_smtp_port_not_null NOT NULL,
    smtp_enable_ssl boolean DEFAULT true CONSTRAINT email_template_smtp_enable_ssl_not_null NOT NULL,
    smtp_user_name text DEFAULT ''::text CONSTRAINT email_template_smtp_user_name_not_null NOT NULL,
    smtp_password text DEFAULT ''::text CONSTRAINT email_template_smtp_password_not_null NOT NULL,
    from_address text DEFAULT ''::text CONSTRAINT email_template_from_address_not_null NOT NULL,
    from_display_name text DEFAULT ''::text CONSTRAINT email_template_from_display_name_not_null NOT NULL,
    date_update timestamp without time zone DEFAULT now() CONSTRAINT email_template_date_update_not_null NOT NULL,
    user_update integer,
    CONSTRAINT ck_email_config_smtp_port CHECK (((smtp_port >= 1) AND (smtp_port <= 65535)))
);


-- Name: email_config_id_config_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.email_config ALTER COLUMN id_config ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.email_config_id_config_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- Name: email_config_l; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.email_config_l (
    id_audit bigint CONSTRAINT email_template_l_id_audit_not_null NOT NULL,
    operation text CONSTRAINT email_template_l_operation_not_null NOT NULL,
    changed_at timestamp without time zone DEFAULT now() CONSTRAINT email_template_l_changed_at_not_null NOT NULL,
    changed_by_user_id integer,
    record_pk jsonb CONSTRAINT email_template_l_record_pk_not_null NOT NULL,
    row_data jsonb CONSTRAINT email_template_l_row_data_not_null NOT NULL
);


-- Name: email_template_l_id_audit_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.email_config_l ALTER COLUMN id_audit ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.email_template_l_id_audit_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- Name: survey_auto_creation_config_l; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.survey_auto_creation_config_l (
    id_audit bigint CONSTRAINT l_survey_auto_creation_config_id_audit_not_null NOT NULL,
    operation text CONSTRAINT l_survey_auto_creation_config_operation_not_null NOT NULL,
    changed_at timestamp without time zone DEFAULT now() CONSTRAINT l_survey_auto_creation_config_changed_at_not_null NOT NULL,
    changed_by_user_id integer,
    record_pk jsonb CONSTRAINT l_survey_auto_creation_config_record_pk_not_null NOT NULL,
    row_data jsonb CONSTRAINT l_survey_auto_creation_config_row_data_not_null NOT NULL
);


-- Name: l_survey_auto_creation_config_id_audit_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.survey_auto_creation_config_l ALTER COLUMN id_audit ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.l_survey_auto_creation_config_id_audit_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- Name: organization; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.organization (
    id_organization integer CONSTRAINT organization_organization_id_not_null NOT NULL,
    organization_name text NOT NULL,
    date_begin date,
    date_end date,
    email text,
    organization_short_name text
);


-- Name: organization_l; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.organization_l (
    id_audit bigint NOT NULL,
    operation text NOT NULL,
    changed_at timestamp without time zone DEFAULT now() NOT NULL,
    changed_by_user_id integer,
    record_pk jsonb NOT NULL,
    row_data jsonb NOT NULL
);


-- Name: organization_l_id_audit_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.organization_l ALTER COLUMN id_audit ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.organization_l_id_audit_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- Name: organization_organization_id_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.organization ALTER COLUMN id_organization ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.organization_organization_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- Name: organization_survey; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.organization_survey (
    id_organization integer CONSTRAINT organization_survey_organization_id_not_null NOT NULL,
    id_survey integer NOT NULL,
    date_begin date CONSTRAINT organization_survey_date_open_not_null NOT NULL,
    date_end date CONSTRAINT organization_survey_date_close_not_null NOT NULL,
    id_organization_survey integer NOT NULL
);


-- Name: organization_survey_id_organization_survey_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.organization_survey ALTER COLUMN id_organization_survey ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.organization_survey_id_organization_survey_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- Name: organization_survey_l; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.organization_survey_l (
    id_audit bigint NOT NULL,
    operation text NOT NULL,
    changed_at timestamp without time zone DEFAULT now() NOT NULL,
    changed_by_user_id integer,
    record_pk jsonb NOT NULL,
    row_data jsonb NOT NULL
);


-- Name: organization_survey_l_id_audit_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.organization_survey_l ALTER COLUMN id_audit ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.organization_survey_l_id_audit_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- Name: survey; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.survey (
    id_survey integer NOT NULL,
    name_survey text NOT NULL,
    description text
);


-- Name: survey_auto_creation_config; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.survey_auto_creation_config (
    id_config integer NOT NULL,
    id_survey integer NOT NULL
);


-- Name: survey_id_survey_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.survey ALTER COLUMN id_survey ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.survey_id_survey_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- Name: survey_l; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.survey_l (
    id_audit bigint NOT NULL,
    operation text NOT NULL,
    changed_at timestamp without time zone DEFAULT now() NOT NULL,
    changed_by_user_id integer,
    record_pk jsonb NOT NULL,
    row_data jsonb NOT NULL
);


-- Name: survey_l_id_audit_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.survey_l ALTER COLUMN id_audit ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.survey_l_id_audit_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- Name: survey_question; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.survey_question (
    id_question integer NOT NULL,
    id_survey integer NOT NULL,
    question_order integer NOT NULL,
    question_text text NOT NULL
);


-- Name: survey_question_id_question_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.survey_question ALTER COLUMN id_question ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.survey_question_id_question_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- Name: survey_schedule; Type: VIEW; Schema: public; Owner: -

CREATE VIEW public.survey_schedule AS
 SELECT s.id_survey,
    min(os.date_begin) AS date_begin,
    max(os.date_end) AS date_end
   FROM (public.survey s
     LEFT JOIN public.organization_survey os ON ((os.id_survey = s.id_survey)))
  GROUP BY s.id_survey;


-- Name: week_day; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.week_day (
    id_day integer NOT NULL,
    en_name_day text NOT NULL,
    rus_name_day text NOT NULL,
    week_number integer NOT NULL,
    CONSTRAINT ck_week_day_en_name CHECK ((en_name_day = ANY (ARRAY['Monday'::text, 'Tuesday'::text, 'Wednesday'::text, 'Thursday'::text, 'Friday'::text]))),
    CONSTRAINT ck_week_day_week_number CHECK (((week_number >= 1) AND (week_number <= 4)))
);


-- Name: answer answer_id_organization_survey_key; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.answer
    ADD CONSTRAINT answer_id_organization_survey_key UNIQUE (id_organization_survey);


-- Name: answer_l answer_l_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.answer_l
    ADD CONSTRAINT answer_l_pkey PRIMARY KEY (id_audit);


-- Name: answer answer_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.answer
    ADD CONSTRAINT answer_pkey PRIMARY KEY (id_answer);


-- Name: app_user_l app_user_l_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.app_user_l
    ADD CONSTRAINT app_user_l_pkey PRIMARY KEY (id_audit);


-- Name: app_user app_user_login_key; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_login_key UNIQUE (login);


-- Name: app_user app_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_pkey PRIMARY KEY (id_user);


-- Name: auto_creation_config auto_creation_config_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.auto_creation_config
    ADD CONSTRAINT auto_creation_config_pkey PRIMARY KEY (id_config);


-- Name: email_config email_config_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.email_config
    ADD CONSTRAINT email_config_pkey PRIMARY KEY (id_config);


-- Name: email_config_l email_template_l_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.email_config_l
    ADD CONSTRAINT email_template_l_pkey PRIMARY KEY (id_audit);


-- Name: answer_item history_answer_item_id_answer_question_order_key; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.answer_item
    ADD CONSTRAINT history_answer_item_id_answer_question_order_key UNIQUE (id_answer, question_order);


-- Name: answer_item history_answer_item_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.answer_item
    ADD CONSTRAINT history_answer_item_pkey PRIMARY KEY (id_item);


-- Name: survey_auto_creation_config_l l_survey_auto_creation_config_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.survey_auto_creation_config_l
    ADD CONSTRAINT l_survey_auto_creation_config_pkey PRIMARY KEY (id_audit);


-- Name: organization_l organization_l_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.organization_l
    ADD CONSTRAINT organization_l_pkey PRIMARY KEY (id_audit);


-- Name: organization organization_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.organization
    ADD CONSTRAINT organization_pkey PRIMARY KEY (id_organization);


-- Name: organization_survey_l organization_survey_l_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.organization_survey_l
    ADD CONSTRAINT organization_survey_l_pkey PRIMARY KEY (id_audit);


-- Name: organization_survey organization_survey_organization_id_survey_key; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.organization_survey
    ADD CONSTRAINT organization_survey_organization_id_survey_key UNIQUE (id_organization, id_survey);


-- Name: organization_survey organization_survey_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.organization_survey
    ADD CONSTRAINT organization_survey_pkey PRIMARY KEY (id_organization_survey);


-- Name: survey_auto_creation_config pk_survey_auto_creation_config; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.survey_auto_creation_config
    ADD CONSTRAINT pk_survey_auto_creation_config PRIMARY KEY (id_config, id_survey);


-- Name: survey_l survey_l_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.survey_l
    ADD CONSTRAINT survey_l_pkey PRIMARY KEY (id_audit);


-- Name: survey survey_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.survey
    ADD CONSTRAINT survey_pkey PRIMARY KEY (id_survey);


-- Name: survey_question survey_question_id_survey_question_order_key; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.survey_question
    ADD CONSTRAINT survey_question_id_survey_question_order_key UNIQUE (id_survey, question_order);


-- Name: survey_question survey_question_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.survey_question
    ADD CONSTRAINT survey_question_pkey PRIMARY KEY (id_question);


-- Name: week_day ux_week_day_name_week; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.week_day
    ADD CONSTRAINT ux_week_day_name_week UNIQUE (en_name_day, week_number);


-- Name: week_day week_day_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.week_day
    ADD CONSTRAINT week_day_pkey PRIMARY KEY (id_day);


-- Name: idx_answer_completion_date; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_answer_completion_date ON public.answer USING btree (completion_date);


-- Name: idx_answer_id_organization_survey; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_answer_id_organization_survey ON public.answer USING btree (id_organization_survey);


-- Name: idx_answer_item_id_answer; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_answer_item_id_answer ON public.answer_item USING btree (id_answer, question_order);


-- Name: idx_answer_l_changed_at; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_answer_l_changed_at ON public.answer_l USING btree (changed_at DESC);


-- Name: idx_answer_l_record_pk; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_answer_l_record_pk ON public.answer_l USING gin (record_pk);


-- Name: idx_app_user_date_end; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_app_user_date_end ON public.app_user USING btree (date_end);


-- Name: idx_app_user_l_changed_at; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_app_user_l_changed_at ON public.app_user_l USING btree (changed_at DESC);


-- Name: idx_app_user_l_record_pk; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_app_user_l_record_pk ON public.app_user_l USING gin (record_pk);


-- Name: idx_app_user_organization_id; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_app_user_organization_id ON public.app_user USING btree (id_organization);


-- Name: idx_email_config_l_changed_at; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_email_config_l_changed_at ON public.email_config_l USING btree (changed_at DESC);


-- Name: idx_email_config_l_record_pk; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_email_config_l_record_pk ON public.email_config_l USING gin (record_pk);


-- Name: idx_organization_date_end; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_organization_date_end ON public.organization USING btree (date_end);


-- Name: idx_organization_l_changed_at; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_organization_l_changed_at ON public.organization_l USING btree (changed_at DESC);


-- Name: idx_organization_l_record_pk; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_organization_l_record_pk ON public.organization_l USING gin (record_pk);


-- Name: idx_organization_survey_id_organization; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_organization_survey_id_organization ON public.organization_survey USING btree (id_organization);


-- Name: idx_organization_survey_id_survey; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_organization_survey_id_survey ON public.organization_survey USING btree (id_survey);


-- Name: idx_organization_survey_l_changed_at; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_organization_survey_l_changed_at ON public.organization_survey_l USING btree (changed_at DESC);


-- Name: idx_organization_survey_l_record_pk; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_organization_survey_l_record_pk ON public.organization_survey_l USING gin (record_pk);


-- Name: idx_survey_auto_creation_config_l_changed_at; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_survey_auto_creation_config_l_changed_at ON public.survey_auto_creation_config_l USING btree (changed_at DESC);


-- Name: idx_survey_auto_creation_config_l_record_pk; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_survey_auto_creation_config_l_record_pk ON public.survey_auto_creation_config_l USING gin (record_pk);


-- Name: idx_survey_l_changed_at; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_survey_l_changed_at ON public.survey_l USING btree (changed_at DESC);


-- Name: idx_survey_l_record_pk; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_survey_l_record_pk ON public.survey_l USING gin (record_pk);


-- Name: idx_survey_question_id_survey; Type: INDEX; Schema: public; Owner: -

CREATE INDEX idx_survey_question_id_survey ON public.survey_question USING btree (id_survey, question_order);


-- Name: answer trg_answer_crud_audit; Type: TRIGGER; Schema: public; Owner: -

CREATE TRIGGER trg_answer_crud_audit AFTER INSERT OR DELETE OR UPDATE ON public.answer FOR EACH ROW EXECUTE FUNCTION public.write_crud_audit('id_answer');


-- Name: app_user trg_app_user_crud_audit; Type: TRIGGER; Schema: public; Owner: -

CREATE TRIGGER trg_app_user_crud_audit AFTER INSERT OR DELETE OR UPDATE ON public.app_user FOR EACH ROW EXECUTE FUNCTION public.write_crud_audit('id_user');


-- Name: email_config trg_email_config_audit; Type: TRIGGER; Schema: public; Owner: -

CREATE TRIGGER trg_email_config_audit AFTER INSERT OR DELETE OR UPDATE ON public.email_config FOR EACH ROW EXECUTE FUNCTION public.write_crud_audit('id_config');


-- Name: email_config trg_email_config_set_update_metadata; Type: TRIGGER; Schema: public; Owner: -

CREATE TRIGGER trg_email_config_set_update_metadata BEFORE INSERT OR UPDATE ON public.email_config FOR EACH ROW EXECUTE FUNCTION public.set_update_metadata();


-- Name: organization trg_organization_crud_audit; Type: TRIGGER; Schema: public; Owner: -

CREATE TRIGGER trg_organization_crud_audit AFTER INSERT OR DELETE OR UPDATE ON public.organization FOR EACH ROW EXECUTE FUNCTION public.write_crud_audit('id_organization');


-- Name: organization_survey trg_organization_survey_crud_audit; Type: TRIGGER; Schema: public; Owner: -

CREATE TRIGGER trg_organization_survey_crud_audit AFTER INSERT OR DELETE OR UPDATE ON public.organization_survey FOR EACH ROW EXECUTE FUNCTION public.write_crud_audit('id_organization_survey');


-- Name: survey_auto_creation_config trg_survey_auto_creation_config_audit; Type: TRIGGER; Schema: public; Owner: -

CREATE TRIGGER trg_survey_auto_creation_config_audit AFTER INSERT OR DELETE OR UPDATE ON public.survey_auto_creation_config FOR EACH ROW EXECUTE FUNCTION public.write_survey_auto_creation_config_audit();


-- Name: survey trg_survey_crud_audit; Type: TRIGGER; Schema: public; Owner: -

CREATE TRIGGER trg_survey_crud_audit AFTER INSERT OR DELETE OR UPDATE ON public.survey FOR EACH ROW EXECUTE FUNCTION public.write_crud_audit('id_survey');


-- Name: answer answer_id_organization_survey_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.answer
    ADD CONSTRAINT answer_id_organization_survey_fkey FOREIGN KEY (id_organization_survey) REFERENCES public.organization_survey(id_organization_survey) ON DELETE CASCADE;


-- Name: app_user app_user_organization_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_organization_id_fkey FOREIGN KEY (id_organization) REFERENCES public.organization(id_organization) ON DELETE SET NULL;


-- Name: auto_creation_config fk_auto_creation_config_begin_day; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.auto_creation_config
    ADD CONSTRAINT fk_auto_creation_config_begin_day FOREIGN KEY (id_begin_day) REFERENCES public.week_day(id_day);


-- Name: auto_creation_config fk_auto_creation_config_creation_day; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.auto_creation_config
    ADD CONSTRAINT fk_auto_creation_config_creation_day FOREIGN KEY (id_creation_day) REFERENCES public.week_day(id_day);


-- Name: survey_auto_creation_config fk_survey_auto_creation_config_config; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.survey_auto_creation_config
    ADD CONSTRAINT fk_survey_auto_creation_config_config FOREIGN KEY (id_config) REFERENCES public.auto_creation_config(id_config) ON DELETE CASCADE;


-- Name: survey_auto_creation_config fk_survey_auto_creation_config_survey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.survey_auto_creation_config
    ADD CONSTRAINT fk_survey_auto_creation_config_survey FOREIGN KEY (id_survey) REFERENCES public.survey(id_survey) ON DELETE CASCADE;


-- Name: answer_item history_answer_item_id_answer_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.answer_item
    ADD CONSTRAINT history_answer_item_id_answer_fkey FOREIGN KEY (id_answer) REFERENCES public.answer(id_answer) ON DELETE CASCADE;


-- Name: organization_survey organization_survey_id_survey_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.organization_survey
    ADD CONSTRAINT organization_survey_id_survey_fkey FOREIGN KEY (id_survey) REFERENCES public.survey(id_survey) ON DELETE CASCADE;


-- Name: organization_survey organization_survey_organization_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.organization_survey
    ADD CONSTRAINT organization_survey_organization_id_fkey FOREIGN KEY (id_organization) REFERENCES public.organization(id_organization) ON DELETE CASCADE;


-- Name: survey_question survey_question_id_survey_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.survey_question
    ADD CONSTRAINT survey_question_id_survey_fkey FOREIGN KEY (id_survey) REFERENCES public.survey(id_survey) ON DELETE CASCADE;




