\set ON_ERROR_STOP on

SELECT CASE
    WHEN EXISTS (SELECT 1 FROM public.schema_migrations WHERE version = '010') THEN 'false'
    ELSE 'true'
END AS apply_migration \gset

\if :apply_migration
\echo Applying migration 010_add_email_template_storage

BEGIN;

CREATE OR REPLACE FUNCTION public.set_update_metadata()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
    NEW.date_update = NOW();

    IF current_setting('app.current_user_id', true) IS NOT NULL
        AND current_setting('app.current_user_id', true) <> ''
    THEN
        NEW.user_update = current_setting('app.current_user_id', true)::integer;
    END IF;

    RETURN NEW;
END;
$function$;

CREATE TABLE IF NOT EXISTS public.email_template (
    id_email_template integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_key text NOT NULL,
    recipient_emails text NOT NULL DEFAULT '',
    subject_text text NOT NULL DEFAULT '',
    body_text text NOT NULL DEFAULT '',
    smtp_host text NOT NULL DEFAULT '',
    smtp_port integer NOT NULL DEFAULT 587,
    smtp_enable_ssl boolean NOT NULL DEFAULT true,
    smtp_user_name text NOT NULL DEFAULT '',
    smtp_password text NOT NULL DEFAULT '',
    from_address text NOT NULL DEFAULT '',
    from_display_name text NOT NULL DEFAULT '',
    date_update timestamp without time zone NOT NULL DEFAULT NOW(),
    user_update integer,
    CONSTRAINT ux_email_template_template_key UNIQUE (template_key),
    CONSTRAINT ck_email_template_smtp_port CHECK (smtp_port BETWEEN 1 AND 65535)
);

CREATE TABLE IF NOT EXISTS public.email_template_l (
    id_audit bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation text NOT NULL,
    changed_at timestamp without time zone NOT NULL DEFAULT NOW(),
    changed_by_user_id integer,
    record_pk jsonb NOT NULL,
    row_data jsonb NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_email_template_l_changed_at
    ON public.email_template_l (changed_at DESC);

CREATE INDEX IF NOT EXISTS idx_email_template_l_record_pk
    ON public.email_template_l USING gin (record_pk);

DROP TRIGGER IF EXISTS trg_email_template_set_update_metadata ON public.email_template;
CREATE TRIGGER trg_email_template_set_update_metadata
BEFORE INSERT OR UPDATE ON public.email_template
FOR EACH ROW
EXECUTE FUNCTION public.set_update_metadata();

DROP TRIGGER IF EXISTS trg_email_template_audit ON public.email_template;
CREATE TRIGGER trg_email_template_audit
AFTER INSERT OR UPDATE OR DELETE ON public.email_template
FOR EACH ROW
EXECUTE FUNCTION public.write_crud_audit('id_email_template');

INSERT INTO public.schema_migrations (version, name)
VALUES ('010', 'add_email_template_storage')
ON CONFLICT (version) DO NOTHING;

COMMIT;
\else
\echo Skipping migration 010_add_email_template_storage
\endif
