\set ON_ERROR_STOP on

SELECT CASE
    WHEN EXISTS (SELECT 1 FROM public.schema_migrations WHERE version = '011') THEN 'false'
    ELSE 'true'
END AS apply_migration \gset

\if :apply_migration
\echo Applying migration 011_add_email_template_audit_log

BEGIN;

CREATE TABLE IF NOT EXISTS public.email_template_l (
    id_audit bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation text NOT NULL,
    changed_at timestamp without time zone NOT NULL DEFAULT NOW(),
    changed_by_user_id integer,
    record_pk jsonb NOT NULL,
    row_data jsonb NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_email_template_l_changed_at
    ON public.email_template_l (changed_at DESC);

CREATE INDEX IF NOT EXISTS idx_email_template_l_record_pk
    ON public.email_template_l USING gin (record_pk);

DROP TRIGGER IF EXISTS trg_email_template_audit ON public.email_template;
CREATE TRIGGER trg_email_template_audit
AFTER INSERT OR UPDATE OR DELETE ON public.email_template
FOR EACH ROW
EXECUTE FUNCTION public.write_crud_audit('id_email_template');

INSERT INTO public.schema_migrations (version, name)
VALUES ('011', 'add_email_template_audit_log')
ON CONFLICT (version) DO NOTHING;

COMMIT;
\else
\echo Skipping migration 011_add_email_template_audit_log
\endif
