\set ON_ERROR_STOP on

SELECT CASE
    WHEN EXISTS (SELECT 1 FROM public.schema_migrations WHERE version = '015') THEN 'false'
    ELSE 'true'
END AS apply_migration \gset

\if :apply_migration
\echo Applying migration 015_link_answers_to_organization_survey

BEGIN;

ALTER TABLE public.organization_survey
    ADD COLUMN IF NOT EXISTS id_organization_survey integer;

DO $$
DECLARE
    max_existing_id integer;
BEGIN
    SELECT COALESCE(MAX(id_organization_survey), 0)
    INTO max_existing_id
    FROM public.organization_survey;

    WITH numbered_assignments AS (
        SELECT
            ctid,
            max_existing_id + ROW_NUMBER() OVER (ORDER BY id_organization, id_survey) AS generated_id
        FROM public.organization_survey
        WHERE id_organization_survey IS NULL
    )
    UPDATE public.organization_survey os
    SET id_organization_survey = numbered_assignments.generated_id
    FROM numbered_assignments
    WHERE os.ctid = numbered_assignments.ctid;
END;
$$;

ALTER TABLE public.organization_survey
    ALTER COLUMN id_organization_survey SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_attribute attr
        INNER JOIN pg_class cls
            ON cls.oid = attr.attrelid
        INNER JOIN pg_namespace ns
            ON ns.oid = cls.relnamespace
        WHERE ns.nspname = 'public'
          AND cls.relname = 'organization_survey'
          AND attr.attname = 'id_organization_survey'
          AND attr.attidentity <> ''
    ) THEN
        EXECUTE 'ALTER TABLE public.organization_survey ALTER COLUMN id_organization_survey ADD GENERATED BY DEFAULT AS IDENTITY';
    END IF;
END;
$$;

INSERT INTO public.organization_survey (id_organization, id_survey, date_begin, date_end)
SELECT DISTINCT
    a.id_organization,
    a.id_survey,
    COALESCE(ss.date_begin, CURRENT_DATE)::date AS date_begin,
    GREATEST(
        COALESCE(ss.date_end, (CURRENT_DATE + INTERVAL '1 day')::date)::date,
        (COALESCE(ss.date_begin, CURRENT_DATE)::date + INTERVAL '1 day')::date
    ) AS date_end
FROM public.answer a
INNER JOIN public.organization o
    ON o.id_organization = a.id_organization
INNER JOIN public.survey s
    ON s.id_survey = a.id_survey
LEFT JOIN public.organization_survey os
    ON os.id_organization = a.id_organization
   AND os.id_survey = a.id_survey
LEFT JOIN public.survey_schedule ss
    ON ss.id_survey = a.id_survey
WHERE os.id_organization IS NULL
ON CONFLICT (id_organization, id_survey) DO NOTHING;

DO $$
DECLARE
    sequence_name text;
    max_id integer;
BEGIN
    SELECT pg_get_serial_sequence('public.organization_survey', 'id_organization_survey')
    INTO sequence_name;

    SELECT COALESCE(MAX(id_organization_survey), 0)
    INTO max_id
    FROM public.organization_survey;

    IF sequence_name IS NOT NULL AND max_id > 0 THEN
        PERFORM setval(sequence_name, max_id, true);
    END IF;
END;
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conrelid = 'public.organization_survey'::regclass
          AND conname = 'organization_survey_organization_id_survey_key'
    ) THEN
        ALTER TABLE public.organization_survey
            ADD CONSTRAINT organization_survey_organization_id_survey_key UNIQUE (id_organization, id_survey);
    END IF;
END;
$$;

ALTER TABLE public.organization_survey
    DROP CONSTRAINT IF EXISTS organization_survey_pkey;

ALTER TABLE public.organization_survey
    ADD CONSTRAINT organization_survey_pkey PRIMARY KEY (id_organization_survey);

ALTER TABLE public.answer
    ADD COLUMN IF NOT EXISTS id_organization_survey integer;

UPDATE public.answer a
SET id_organization_survey = os.id_organization_survey
FROM public.organization_survey os
WHERE a.id_organization_survey IS NULL
  AND os.id_organization = a.id_organization
  AND os.id_survey = a.id_survey;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM public.answer
        WHERE id_organization_survey IS NULL
    ) THEN
        RAISE EXCEPTION 'Не удалось связать часть ответов с назначениями анкет.';
    END IF;
END;
$$;

ALTER TABLE public.answer
    ALTER COLUMN id_organization_survey SET NOT NULL;

ALTER TABLE public.answer
    DROP CONSTRAINT IF EXISTS history_answer_organization_survey_key,
    DROP CONSTRAINT IF EXISTS answer_id_survey_fkey,
    DROP CONSTRAINT IF EXISTS history_answer_organization_id_fkey;

DROP INDEX IF EXISTS public.idx_answer_id_survey;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conrelid = 'public.answer'::regclass
          AND conname = 'answer_id_organization_survey_key'
    ) THEN
        ALTER TABLE public.answer
            ADD CONSTRAINT answer_id_organization_survey_key UNIQUE (id_organization_survey);
    END IF;
END;
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conrelid = 'public.answer'::regclass
          AND conname = 'answer_id_organization_survey_fkey'
    ) THEN
        ALTER TABLE public.answer
            ADD CONSTRAINT answer_id_organization_survey_fkey
            FOREIGN KEY (id_organization_survey)
            REFERENCES public.organization_survey (id_organization_survey)
            ON DELETE CASCADE;
    END IF;
END;
$$;

ALTER TABLE public.answer
    DROP COLUMN IF EXISTS id_organization,
    DROP COLUMN IF EXISTS id_survey;

DROP TRIGGER IF EXISTS trg_organization_survey_crud_audit ON public.organization_survey;
CREATE TRIGGER trg_organization_survey_crud_audit
AFTER INSERT OR DELETE OR UPDATE ON public.organization_survey
FOR EACH ROW
EXECUTE FUNCTION public.write_crud_audit('id_organization_survey');

CREATE INDEX IF NOT EXISTS idx_answer_id_organization_survey
    ON public.answer (id_organization_survey);

CREATE INDEX IF NOT EXISTS idx_organization_survey_id_organization
    ON public.organization_survey (id_organization);

CREATE INDEX IF NOT EXISTS idx_organization_survey_id_survey
    ON public.organization_survey (id_survey);

INSERT INTO public.schema_migrations (version, name)
VALUES ('015', 'link_answers_to_organization_survey')
ON CONFLICT (version) DO NOTHING;

COMMIT;
\else
\echo Skipping migration 015_link_answers_to_organization_survey
\endif
