\set ON_ERROR_STOP on

SELECT CASE
    WHEN EXISTS (SELECT 1 FROM public.schema_migrations WHERE version = '016') THEN 'false'
    ELSE 'true'
END AS apply_migration \gset

\if :apply_migration
\echo Applying migration 016_rename_config_tables

BEGIN;

DO $$
BEGIN
    IF to_regclass('public.email_template') IS NOT NULL
       AND to_regclass('public.email_config') IS NULL THEN
        ALTER TABLE public.email_template RENAME TO email_config;
    END IF;

    IF to_regclass('public.email_template_l') IS NOT NULL
       AND to_regclass('public.email_config_l') IS NULL THEN
        ALTER TABLE public.email_template_l RENAME TO email_config_l;
    END IF;

    IF to_regclass('public.l_survey_auto_creation_config') IS NOT NULL
       AND to_regclass('public.survey_auto_creation_config_l') IS NULL THEN
        ALTER TABLE public.l_survey_auto_creation_config RENAME TO survey_auto_creation_config_l;
    END IF;
END;
$$;

DO $$
BEGIN
    IF to_regclass('public.email_config') IS NOT NULL THEN
        IF EXISTS (
            SELECT 1
            FROM information_schema.columns
            WHERE table_schema = 'public'
              AND table_name = 'email_config'
              AND column_name = 'id_email_template'
        ) AND NOT EXISTS (
            SELECT 1
            FROM information_schema.columns
            WHERE table_schema = 'public'
              AND table_name = 'email_config'
              AND column_name = 'id_config'
        ) THEN
            ALTER TABLE public.email_config RENAME COLUMN id_email_template TO id_config;
        END IF;

        ALTER TABLE public.email_config
            DROP CONSTRAINT IF EXISTS ux_email_template_template_key;

        ALTER TABLE public.email_config
            DROP COLUMN IF EXISTS template_key;

        IF EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conrelid = 'public.email_config'::regclass
              AND conname = 'email_template_pkey'
        ) THEN
            ALTER TABLE public.email_config
                RENAME CONSTRAINT email_template_pkey TO email_config_pkey;
        END IF;

        IF EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conrelid = 'public.email_config'::regclass
              AND conname = 'ck_email_template_smtp_port'
        ) THEN
            ALTER TABLE public.email_config
                RENAME CONSTRAINT ck_email_template_smtp_port TO ck_email_config_smtp_port;
        END IF;
    END IF;
END;
$$;

DO $$
BEGIN
    IF to_regclass('public.idx_email_template_l_changed_at') IS NOT NULL
       AND to_regclass('public.idx_email_config_l_changed_at') IS NULL THEN
        ALTER INDEX public.idx_email_template_l_changed_at RENAME TO idx_email_config_l_changed_at;
    END IF;

    IF to_regclass('public.idx_email_template_l_record_pk') IS NOT NULL
       AND to_regclass('public.idx_email_config_l_record_pk') IS NULL THEN
        ALTER INDEX public.idx_email_template_l_record_pk RENAME TO idx_email_config_l_record_pk;
    END IF;

    IF to_regclass('public.idx_l_survey_auto_creation_config_changed_at') IS NOT NULL
       AND to_regclass('public.idx_survey_auto_creation_config_l_changed_at') IS NULL THEN
        ALTER INDEX public.idx_l_survey_auto_creation_config_changed_at RENAME TO idx_survey_auto_creation_config_l_changed_at;
    END IF;

    IF to_regclass('public.idx_l_survey_auto_creation_config_record_pk') IS NOT NULL
       AND to_regclass('public.idx_survey_auto_creation_config_l_record_pk') IS NULL THEN
        ALTER INDEX public.idx_l_survey_auto_creation_config_record_pk RENAME TO idx_survey_auto_creation_config_l_record_pk;
    END IF;

    IF to_regclass('public.email_template_id_email_template_seq') IS NOT NULL
       AND to_regclass('public.email_config_id_config_seq') IS NULL THEN
        ALTER SEQUENCE public.email_template_id_email_template_seq RENAME TO email_config_id_config_seq;
    END IF;
END;
$$;

DO $$
BEGIN
    IF to_regclass('public.email_config') IS NOT NULL THEN
        DROP TRIGGER IF EXISTS trg_email_template_set_update_metadata ON public.email_config;
        DROP TRIGGER IF EXISTS trg_email_config_set_update_metadata ON public.email_config;
        CREATE TRIGGER trg_email_config_set_update_metadata
        BEFORE INSERT OR UPDATE ON public.email_config
        FOR EACH ROW
        EXECUTE FUNCTION public.set_update_metadata();

        DROP TRIGGER IF EXISTS trg_email_template_audit ON public.email_config;
        DROP TRIGGER IF EXISTS trg_email_config_audit ON public.email_config;
        CREATE TRIGGER trg_email_config_audit
        AFTER INSERT OR UPDATE OR DELETE ON public.email_config
        FOR EACH ROW
        EXECUTE FUNCTION public.write_crud_audit('id_config');
    END IF;
END;
$$;

CREATE TABLE IF NOT EXISTS public.email_config_l (
    id_audit bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation text NOT NULL,
    changed_at timestamp without time zone NOT NULL DEFAULT NOW(),
    changed_by_user_id integer,
    record_pk jsonb NOT NULL,
    row_data jsonb NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_email_config_l_changed_at
    ON public.email_config_l (changed_at DESC);

CREATE INDEX IF NOT EXISTS idx_email_config_l_record_pk
    ON public.email_config_l USING gin (record_pk);

CREATE TABLE IF NOT EXISTS public.survey_auto_creation_config_l (
    id_audit bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation text NOT NULL,
    changed_at timestamp without time zone NOT NULL DEFAULT NOW(),
    changed_by_user_id integer,
    record_pk jsonb NOT NULL,
    row_data jsonb NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_survey_auto_creation_config_l_changed_at
    ON public.survey_auto_creation_config_l (changed_at DESC);

CREATE INDEX IF NOT EXISTS idx_survey_auto_creation_config_l_record_pk
    ON public.survey_auto_creation_config_l USING gin (record_pk);

CREATE OR REPLACE FUNCTION public.write_survey_auto_creation_config_audit()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
DECLARE
    changed_by integer;
    audit_record_pk jsonb;
    audit_row_data jsonb;
BEGIN
    IF current_setting('app.current_user_id', true) IS NOT NULL
        AND current_setting('app.current_user_id', true) <> ''
    THEN
        changed_by := current_setting('app.current_user_id', true)::integer;
    END IF;

    IF TG_OP = 'DELETE' THEN
        audit_record_pk := jsonb_build_object('id_config', OLD.id_config, 'id_survey', OLD.id_survey);
        audit_row_data := to_jsonb(OLD);
    ELSE
        audit_record_pk := jsonb_build_object('id_config', NEW.id_config, 'id_survey', NEW.id_survey);
        audit_row_data := to_jsonb(NEW);
    END IF;

    INSERT INTO public.survey_auto_creation_config_l
    (
        operation,
        changed_by_user_id,
        record_pk,
        row_data
    )
    VALUES
    (
        TG_OP,
        changed_by,
        audit_record_pk,
        audit_row_data
    );

    RETURN COALESCE(NEW, OLD);
END;
$function$;

DROP TRIGGER IF EXISTS trg_survey_auto_creation_config_audit ON public.survey_auto_creation_config;
CREATE TRIGGER trg_survey_auto_creation_config_audit
AFTER INSERT OR UPDATE OR DELETE ON public.survey_auto_creation_config
FOR EACH ROW
EXECUTE FUNCTION public.write_survey_auto_creation_config_audit();

INSERT INTO public.schema_migrations (version, name)
VALUES ('016', 'rename_config_tables')
ON CONFLICT (version) DO NOTHING;

COMMIT;
\else
\echo Skipping migration 016_rename_config_tables
\endif
