\set ON_ERROR_STOP on

SELECT CASE
    WHEN EXISTS (SELECT 1 FROM public.schema_migrations WHERE version = '018') THEN 'false'
    ELSE 'true'
END AS apply_migration \gset

\if :apply_migration
\echo Applying migration 018_add_audit_log_current_tables

BEGIN;

CREATE TABLE IF NOT EXISTS public.survey_question_l (
    id_audit bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation text NOT NULL,
    changed_at timestamp without time zone NOT NULL DEFAULT NOW(),
    changed_by_user_id integer,
    record_pk jsonb NOT NULL,
    row_data jsonb NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_survey_question_l_changed_at
    ON public.survey_question_l (changed_at DESC);

CREATE INDEX IF NOT EXISTS idx_survey_question_l_record_pk
    ON public.survey_question_l USING gin (record_pk);

DROP TRIGGER IF EXISTS trg_survey_question_crud_audit ON public.survey_question;
CREATE TRIGGER trg_survey_question_crud_audit
AFTER INSERT OR UPDATE OR DELETE ON public.survey_question
FOR EACH ROW
EXECUTE FUNCTION public.write_crud_audit('id_question');

CREATE TABLE IF NOT EXISTS public.answer_item_l (
    id_audit bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation text NOT NULL,
    changed_at timestamp without time zone NOT NULL DEFAULT NOW(),
    changed_by_user_id integer,
    record_pk jsonb NOT NULL,
    row_data jsonb NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_answer_item_l_changed_at
    ON public.answer_item_l (changed_at DESC);

CREATE INDEX IF NOT EXISTS idx_answer_item_l_record_pk
    ON public.answer_item_l USING gin (record_pk);

DROP TRIGGER IF EXISTS trg_answer_item_crud_audit ON public.answer_item;
CREATE TRIGGER trg_answer_item_crud_audit
AFTER INSERT OR UPDATE OR DELETE ON public.answer_item
FOR EACH ROW
EXECUTE FUNCTION public.write_crud_audit('id_item');

CREATE TABLE IF NOT EXISTS public.auto_creation_config_l (
    id_audit bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation text NOT NULL,
    changed_at timestamp without time zone NOT NULL DEFAULT NOW(),
    changed_by_user_id integer,
    record_pk jsonb NOT NULL,
    row_data jsonb NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_auto_creation_config_l_changed_at
    ON public.auto_creation_config_l (changed_at DESC);

CREATE INDEX IF NOT EXISTS idx_auto_creation_config_l_record_pk
    ON public.auto_creation_config_l USING gin (record_pk);

DROP TRIGGER IF EXISTS trg_auto_creation_config_audit ON public.auto_creation_config;
CREATE TRIGGER trg_auto_creation_config_audit
AFTER INSERT OR UPDATE OR DELETE ON public.auto_creation_config
FOR EACH ROW
EXECUTE FUNCTION public.write_crud_audit('id_config');

INSERT INTO public.schema_migrations (version, name)
VALUES ('018', 'add_audit_log_current_tables')
ON CONFLICT (version) DO NOTHING;

COMMIT;
\else
\echo Skipping migration 018_add_audit_log_current_tables
\endif
