\set ON_ERROR_STOP on

CREATE TABLE IF NOT EXISTS public.schema_migrations (
    version text PRIMARY KEY,
    name text NOT NULL,
    applied_at timestamp without time zone NOT NULL DEFAULT NOW(),
    date_update timestamp without time zone NOT NULL DEFAULT NOW(),
    user_update integer
);

SELECT CASE
    WHEN EXISTS (SELECT 1 FROM public.schema_migrations WHERE version = '023') THEN 'false'
    ELSE 'true'
END AS apply_migration \gset

\if :apply_migration
\echo Applying migration 023_add_theme_config

BEGIN;

CREATE TABLE IF NOT EXISTS public.theme_config (
    id_config integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    font_color text NOT NULL DEFAULT '#343D4B',
    background_color text NOT NULL DEFAULT '#B2A8FF',
    gradient_enabled boolean NOT NULL DEFAULT true,
    gradient_start_color text NOT NULL DEFAULT '#B2A8FF',
    gradient_end_color text NOT NULL DEFAULT '#B2A8FF',
    effect_snow boolean NOT NULL DEFAULT false,
    effect_fireworks boolean NOT NULL DEFAULT false,
    effect_grass boolean NOT NULL DEFAULT false,
    effect_rain boolean NOT NULL DEFAULT false,
    background_image_data_url text NOT NULL DEFAULT '',
    background_image_opacity integer NOT NULL DEFAULT 35,
    date_update timestamp without time zone NOT NULL DEFAULT NOW(),
    user_update integer,
    CONSTRAINT ck_theme_config_background_image_opacity CHECK (background_image_opacity BETWEEN 0 AND 100)
);

CREATE TABLE IF NOT EXISTS public.theme_config_l (
    id_audit bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation text NOT NULL,
    changed_at timestamp without time zone NOT NULL DEFAULT NOW(),
    changed_by_user_id integer,
    record_pk jsonb NOT NULL,
    row_data jsonb NOT NULL,
    old_row_data jsonb,
    new_row_data jsonb
);

CREATE INDEX IF NOT EXISTS idx_theme_config_l_changed_at
    ON public.theme_config_l (changed_at DESC);

CREATE INDEX IF NOT EXISTS idx_theme_config_l_record_pk
    ON public.theme_config_l USING gin (record_pk);

DROP TRIGGER IF EXISTS trg_theme_config_set_update_metadata ON public.theme_config;
CREATE TRIGGER trg_theme_config_set_update_metadata
BEFORE INSERT OR UPDATE ON public.theme_config
FOR EACH ROW
EXECUTE FUNCTION public.set_update_metadata();

DROP TRIGGER IF EXISTS trg_theme_config_audit ON public.theme_config;
CREATE TRIGGER trg_theme_config_audit
AFTER INSERT OR UPDATE OR DELETE ON public.theme_config
FOR EACH ROW
EXECUTE FUNCTION public.write_crud_audit('id_config');

INSERT INTO public.theme_config
(
    id_config,
    font_color,
    background_color,
    gradient_enabled,
    gradient_start_color,
    gradient_end_color,
    effect_snow,
    effect_fireworks,
    effect_grass,
    effect_rain,
    background_image_data_url,
    background_image_opacity
)
VALUES
(
    1,
    '#343D4B',
    '#B2A8FF',
    true,
    '#B2A8FF',
    '#B2A8FF',
    false,
    false,
    false,
    false,
    '',
    35
)
ON CONFLICT (id_config) DO NOTHING;

INSERT INTO public.schema_migrations (version, name)
VALUES ('023', 'add_theme_config')
ON CONFLICT (version) DO NOTHING;

COMMIT;

\else
\echo Skipping migration 023_add_theme_config
\endif
