\set ON_ERROR_STOP on

CREATE TABLE IF NOT EXISTS public.schema_migrations (
    version text PRIMARY KEY,
    name text NOT NULL,
    applied_at timestamp without time zone NOT NULL DEFAULT NOW(),
    date_update timestamp without time zone NOT NULL DEFAULT NOW(),
    user_update integer
);

SELECT CASE
    WHEN EXISTS (SELECT 1 FROM public.schema_migrations WHERE version = '025') THEN 'false'
    ELSE 'true'
END AS apply_migration \gset

\if :apply_migration
\echo Applying migration 025_add_answer_drafts

BEGIN;

CREATE TABLE IF NOT EXISTS public.answer_draft (
    id_answer_draft integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_organization_survey integer NOT NULL,
    draft_date timestamp without time zone NOT NULL DEFAULT NOW(),
    csp text,
    signed_content bytea,
    CONSTRAINT answer_draft_id_organization_survey_key UNIQUE (id_organization_survey),
    CONSTRAINT answer_draft_id_organization_survey_fkey
        FOREIGN KEY (id_organization_survey)
        REFERENCES public.organization_survey(id_organization_survey)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.answer_draft_item (
    id_draft_item integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_answer_draft integer NOT NULL,
    question_order integer NOT NULL,
    question_text text NOT NULL,
    rating integer,
    comment text,
    CONSTRAINT answer_draft_item_rating_check CHECK (rating IS NULL OR rating BETWEEN 1 AND 5),
    CONSTRAINT answer_draft_item_answer_order_key UNIQUE (id_answer_draft, question_order),
    CONSTRAINT answer_draft_item_id_answer_draft_fkey
        FOREIGN KEY (id_answer_draft)
        REFERENCES public.answer_draft(id_answer_draft)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_answer_draft_id_organization_survey
    ON public.answer_draft USING btree (id_organization_survey);

CREATE INDEX IF NOT EXISTS idx_answer_draft_item_id_answer_draft
    ON public.answer_draft_item USING btree (id_answer_draft, question_order);

INSERT INTO public.schema_migrations (version, name)
VALUES ('025', 'add_answer_drafts')
ON CONFLICT (version) DO NOTHING;

COMMIT;

\else
\echo Skipping migration 025_add_answer_drafts
\endif
