\set ON_ERROR_STOP on

CREATE TABLE IF NOT EXISTS public.schema_migrations (
    version text PRIMARY KEY,
    name text NOT NULL,
    applied_at timestamp without time zone NOT NULL DEFAULT NOW()
);

SELECT CASE
    WHEN EXISTS (SELECT 1 FROM public.schema_migrations WHERE version = '047') THEN 'false'
    ELSE 'true'
END AS apply_migration \gset

\if :apply_migration
\echo Applying migration 047_split_survey_templates

BEGIN;

DO $migration$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM public.answer answer
        INNER JOIN public.organization_survey assignment
            ON assignment.id_organization_survey = answer.id_organization_survey
        INNER JOIN public.survey survey
            ON survey.id_survey = assignment.id_survey
        WHERE survey.is_template = true
    ) THEN
        RAISE EXCEPTION
            'Cannot split survey templates: at least one template has a submitted answer.';
    END IF;
END;
$migration$;

CREATE TABLE IF NOT EXISTS public.survey_template (
    id_survey_template integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_survey_template text NOT NULL,
    description text,
    date_begin date NOT NULL,
    date_end date NOT NULL,
    CONSTRAINT survey_template_date_range_check CHECK (date_end > date_begin)
);

CREATE TABLE IF NOT EXISTS public.survey_template_question (
    id_survey_template_question integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_survey_template integer NOT NULL,
    question_order integer NOT NULL,
    question_text text NOT NULL,
    CONSTRAINT survey_template_question_template_order_key
        UNIQUE (id_survey_template, question_order),
    CONSTRAINT survey_template_question_id_survey_template_fkey
        FOREIGN KEY (id_survey_template)
        REFERENCES public.survey_template(id_survey_template)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.organization_survey_template (
    id_organization_survey_template integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_organization integer NOT NULL,
    id_survey_template integer NOT NULL,
    CONSTRAINT organization_survey_template_organization_template_key
        UNIQUE (id_organization, id_survey_template),
    CONSTRAINT organization_survey_template_id_organization_fkey
        FOREIGN KEY (id_organization)
        REFERENCES public.organization(id_organization)
        ON DELETE RESTRICT,
    CONSTRAINT organization_survey_template_id_survey_template_fkey
        FOREIGN KEY (id_survey_template)
        REFERENCES public.survey_template(id_survey_template)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_survey_template_dates
    ON public.survey_template (date_begin, date_end, id_survey_template);

CREATE INDEX IF NOT EXISTS idx_survey_template_question_template
    ON public.survey_template_question (id_survey_template, question_order);

CREATE INDEX IF NOT EXISTS idx_organization_survey_template_template
    ON public.organization_survey_template (id_survey_template, id_organization);

CREATE INDEX IF NOT EXISTS idx_organization_survey_template_organization
    ON public.organization_survey_template (id_organization, id_survey_template);

CREATE TABLE IF NOT EXISTS public.survey_template_l (
    id_audit bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation text NOT NULL,
    changed_at timestamp without time zone NOT NULL DEFAULT NOW(),
    changed_by_user_id integer,
    parent_audit_id bigint,
    id_survey_template integer,
    name_survey_template text,
    description text,
    date_begin date,
    date_end date
);

CREATE TABLE IF NOT EXISTS public.survey_template_question_l (
    id_audit bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation text NOT NULL,
    changed_at timestamp without time zone NOT NULL DEFAULT NOW(),
    changed_by_user_id integer,
    parent_audit_id bigint,
    id_survey_template_question integer,
    id_survey_template integer,
    question_order integer,
    question_text text
);

CREATE TABLE IF NOT EXISTS public.organization_survey_template_l (
    id_audit bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation text NOT NULL,
    changed_at timestamp without time zone NOT NULL DEFAULT NOW(),
    changed_by_user_id integer,
    parent_audit_id bigint,
    id_organization_survey_template integer,
    id_organization integer,
    id_survey_template integer
);

CREATE INDEX IF NOT EXISTS idx_survey_template_l_changed_at_id
    ON public.survey_template_l (changed_at DESC, id_audit DESC);
CREATE INDEX IF NOT EXISTS idx_survey_template_l_parent_audit_id
    ON public.survey_template_l (parent_audit_id);
CREATE INDEX IF NOT EXISTS idx_survey_template_l_record_key
    ON public.survey_template_l (id_survey_template);

CREATE INDEX IF NOT EXISTS idx_survey_template_question_l_changed_at_id
    ON public.survey_template_question_l (changed_at DESC, id_audit DESC);
CREATE INDEX IF NOT EXISTS idx_survey_template_question_l_parent_audit_id
    ON public.survey_template_question_l (parent_audit_id);
CREATE INDEX IF NOT EXISTS idx_survey_template_question_l_record_key
    ON public.survey_template_question_l (id_survey_template_question);

CREATE INDEX IF NOT EXISTS idx_organization_survey_template_l_changed_at_id
    ON public.organization_survey_template_l (changed_at DESC, id_audit DESC);
CREATE INDEX IF NOT EXISTS idx_organization_survey_template_l_parent_audit_id
    ON public.organization_survey_template_l (parent_audit_id);
CREATE INDEX IF NOT EXISTS idx_organization_survey_template_l_record_key
    ON public.organization_survey_template_l (id_organization_survey_template);

DROP TRIGGER IF EXISTS trg_survey_template_crud_audit ON public.survey_template;
CREATE TRIGGER trg_survey_template_crud_audit
AFTER INSERT OR UPDATE OR DELETE ON public.survey_template
FOR EACH ROW
EXECUTE FUNCTION public.write_crud_audit('id_survey_template');

DROP TRIGGER IF EXISTS trg_survey_template_question_crud_audit ON public.survey_template_question;
CREATE TRIGGER trg_survey_template_question_crud_audit
AFTER INSERT OR UPDATE OR DELETE ON public.survey_template_question
FOR EACH ROW
EXECUTE FUNCTION public.write_crud_audit('id_survey_template_question');

DROP TRIGGER IF EXISTS trg_organization_survey_template_crud_audit ON public.organization_survey_template;
CREATE TRIGGER trg_organization_survey_template_crud_audit
AFTER INSERT OR UPDATE OR DELETE ON public.organization_survey_template
FOR EACH ROW
EXECUTE FUNCTION public.write_crud_audit('id_organization_survey_template');

CREATE TEMP TABLE migrated_survey_templates ON COMMIT DROP AS
SELECT id_survey
FROM public.survey
WHERE is_template = true;

CREATE TEMP TABLE migrated_survey_template_questions ON COMMIT DROP AS
SELECT question.id_question
FROM public.survey_question question
INNER JOIN migrated_survey_templates template
    ON template.id_survey = question.id_survey;

CREATE TEMP TABLE migrated_organization_survey_templates ON COMMIT DROP AS
SELECT assignment.id_organization_survey
FROM public.organization_survey assignment
INNER JOIN migrated_survey_templates template
    ON template.id_survey = assignment.id_survey;

INSERT INTO public.survey_template (
    id_survey_template,
    name_survey_template,
    description,
    date_begin,
    date_end
)
SELECT
    survey.id_survey,
    survey.name_survey,
    survey.description,
    survey.date_begin,
    survey.date_end
FROM public.survey survey
INNER JOIN migrated_survey_templates template
    ON template.id_survey = survey.id_survey
ON CONFLICT (id_survey_template) DO UPDATE
SET
    name_survey_template = EXCLUDED.name_survey_template,
    description = EXCLUDED.description,
    date_begin = EXCLUDED.date_begin,
    date_end = EXCLUDED.date_end;

INSERT INTO public.survey_template_question (
    id_survey_template_question,
    id_survey_template,
    question_order,
    question_text
)
SELECT
    question.id_question,
    question.id_survey,
    question.question_order,
    question.question_text
FROM public.survey_question question
INNER JOIN migrated_survey_templates template
    ON template.id_survey = question.id_survey
ON CONFLICT (id_survey_template_question) DO UPDATE
SET
    id_survey_template = EXCLUDED.id_survey_template,
    question_order = EXCLUDED.question_order,
    question_text = EXCLUDED.question_text;

INSERT INTO public.organization_survey_template (
    id_organization_survey_template,
    id_organization,
    id_survey_template
)
SELECT
    assignment.id_organization_survey,
    assignment.id_organization,
    assignment.id_survey
FROM public.organization_survey assignment
INNER JOIN migrated_survey_templates template
    ON template.id_survey = assignment.id_survey
ON CONFLICT (id_organization_survey_template) DO UPDATE
SET
    id_organization = EXCLUDED.id_organization,
    id_survey_template = EXCLUDED.id_survey_template;

SELECT setval(
    pg_get_serial_sequence('public.survey_template', 'id_survey_template'),
    GREATEST(COALESCE((SELECT MAX(id_survey_template) FROM public.survey_template), 0), 1),
    EXISTS (SELECT 1 FROM public.survey_template)
);
SELECT setval(
    pg_get_serial_sequence('public.survey_template_question', 'id_survey_template_question'),
    GREATEST(COALESCE((SELECT MAX(id_survey_template_question) FROM public.survey_template_question), 0), 1),
    EXISTS (SELECT 1 FROM public.survey_template_question)
);
SELECT setval(
    pg_get_serial_sequence('public.organization_survey_template', 'id_organization_survey_template'),
    GREATEST(COALESCE((SELECT MAX(id_organization_survey_template) FROM public.organization_survey_template), 0), 1),
    EXISTS (SELECT 1 FROM public.organization_survey_template)
);

DELETE FROM public.answer_draft draft
USING migrated_organization_survey_templates assignment
WHERE assignment.id_organization_survey = draft.id_organization_survey;

DELETE FROM public.organization_survey assignment
USING migrated_survey_templates template
WHERE assignment.id_survey = template.id_survey;

DELETE FROM public.survey survey
USING migrated_survey_templates template
WHERE survey.id_survey = template.id_survey;

DELETE FROM public.organization_survey_l audit
USING migrated_organization_survey_templates assignment
WHERE audit.id_organization_survey = assignment.id_organization_survey;

DELETE FROM public.survey_question_l audit
USING migrated_survey_template_questions question
WHERE audit.id_question = question.id_question;

DELETE FROM public.survey_l audit
USING migrated_survey_templates template
WHERE audit.id_survey = template.id_survey;

DROP INDEX IF EXISTS public.idx_survey_template_period;

ALTER TABLE public.survey
    DROP COLUMN IF EXISTS is_template;

ALTER TABLE public.survey_l
    DROP COLUMN IF EXISTS is_template;

INSERT INTO public.schema_migrations (version, name)
VALUES ('047', 'split_survey_templates')
ON CONFLICT (version) DO NOTHING;

COMMIT;

\else
\echo Skipping migration 047_split_survey_templates
\endif
