\set ON_ERROR_STOP on

CREATE TABLE IF NOT EXISTS public.schema_migrations (
    version text PRIMARY KEY,
    name text NOT NULL,
    applied_at timestamp without time zone NOT NULL DEFAULT NOW()
);

SELECT CASE
    WHEN EXISTS (SELECT 1 FROM public.schema_migrations WHERE version = '049') THEN 'false'
    ELSE 'true'
END AS apply_migration \gset

\if :apply_migration
\echo Applying migration 049_use_templates_for_auto_creation

BEGIN;

CREATE TEMP TABLE migrated_auto_creation_templates (
    id_config integer NOT NULL,
    normalized_name text NOT NULL,
    PRIMARY KEY (id_config, normalized_name)
) ON COMMIT DROP;

DO $migration$
BEGIN
    IF to_regclass('public.survey_auto_creation_config') IS NOT NULL THEN
        INSERT INTO migrated_auto_creation_templates (id_config, normalized_name)
        SELECT DISTINCT
            selection.id_config,
            lower(btrim(survey.name_survey))
        FROM public.survey_auto_creation_config selection
        INNER JOIN public.survey survey
            ON survey.id_survey = selection.id_survey
        WHERE NULLIF(btrim(survey.name_survey), '') IS NOT NULL
        ON CONFLICT DO NOTHING;
    END IF;
END;
$migration$;

DO $migration$
BEGIN
    IF to_regclass('public.survey_auto_creation_config') IS NOT NULL THEN
        DROP TRIGGER IF EXISTS trg_survey_auto_creation_config_audit
            ON public.survey_auto_creation_config;
    END IF;
END;
$migration$;
DROP TABLE IF EXISTS public.survey_auto_creation_config;

DO $migration$
BEGIN
    IF to_regclass('public.survey_auto_creation_config_l') IS NOT NULL
       AND to_regclass('public.survey_template_auto_creation_config_l') IS NULL THEN
        ALTER TABLE public.survey_auto_creation_config_l
            RENAME TO survey_template_auto_creation_config_l;
    END IF;

    IF to_regclass('public.survey_template_auto_creation_config_l') IS NOT NULL
       AND EXISTS (
            SELECT 1
            FROM information_schema.columns
            WHERE table_schema = 'public'
              AND table_name = 'survey_template_auto_creation_config_l'
              AND column_name = 'id_survey'
       ) THEN
        ALTER TABLE public.survey_template_auto_creation_config_l
            RENAME COLUMN id_survey TO id_survey_template;
    END IF;
END;
$migration$;

CREATE TABLE IF NOT EXISTS public.survey_template_auto_creation_config (
    id_config integer NOT NULL,
    id_survey_template integer NOT NULL,
    CONSTRAINT pk_survey_template_auto_creation_config
        PRIMARY KEY (id_config, id_survey_template),
    CONSTRAINT fk_survey_template_auto_creation_config_config
        FOREIGN KEY (id_config)
        REFERENCES public.auto_creation_config(id_config)
        ON DELETE CASCADE,
    CONSTRAINT fk_survey_template_auto_creation_config_template
        FOREIGN KEY (id_survey_template)
        REFERENCES public.survey_template(id_survey_template)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.survey_template_auto_creation_config_l (
    id_audit bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation text NOT NULL,
    changed_at timestamp without time zone NOT NULL DEFAULT NOW(),
    changed_by_user_id integer,
    parent_audit_id bigint,
    id_config integer,
    id_survey_template integer
);

CREATE INDEX IF NOT EXISTS idx_survey_template_auto_creation_config_template
    ON public.survey_template_auto_creation_config (id_survey_template, id_config);
CREATE INDEX IF NOT EXISTS idx_survey_template_auto_creation_config_l_changed_at
    ON public.survey_template_auto_creation_config_l (changed_at DESC, id_audit DESC);
CREATE INDEX IF NOT EXISTS idx_survey_template_auto_creation_config_l_parent_audit_id
    ON public.survey_template_auto_creation_config_l (parent_audit_id);
CREATE INDEX IF NOT EXISTS idx_survey_template_auto_creation_config_l_record_key
    ON public.survey_template_auto_creation_config_l (id_config, id_survey_template);

INSERT INTO public.survey_template_auto_creation_config (id_config, id_survey_template)
SELECT
    migrated.id_config,
    template.id_survey_template
FROM migrated_auto_creation_templates migrated
CROSS JOIN LATERAL (
    SELECT candidate.id_survey_template
    FROM public.survey_template candidate
    WHERE lower(btrim(candidate.name_survey_template)) = migrated.normalized_name
    ORDER BY candidate.id_survey_template DESC
    LIMIT 1
) template
ON CONFLICT DO NOTHING;

DROP TRIGGER IF EXISTS trg_survey_template_auto_creation_config_crud_audit
    ON public.survey_template_auto_creation_config;
CREATE TRIGGER trg_survey_template_auto_creation_config_crud_audit
AFTER INSERT OR UPDATE OR DELETE ON public.survey_template_auto_creation_config
FOR EACH ROW
EXECUTE FUNCTION public.write_crud_audit('id_config', 'id_survey_template');

DROP FUNCTION IF EXISTS public.write_survey_auto_creation_config_audit();

INSERT INTO public.schema_migrations (version, name)
VALUES ('049', 'use_templates_for_auto_creation')
ON CONFLICT (version) DO NOTHING;

COMMIT;

\else
\echo Skipping migration 049_use_templates_for_auto_creation
\endif
