BEGIN;

-- Reconstructed from the runtime SQL and bootstrapper logic.
-- The schema below reflects the unified model without history tables:
-- surveys stay in public.survey, answers stay in public.answer,
-- and per-organization extensions are stored in public.organization_survey.extended_until.

CREATE TABLE IF NOT EXISTS public.organization (
    organization_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_name text NOT NULL,
    date_begin date,
    date_end date,
    block boolean NOT NULL DEFAULT false,
    email text
);

CREATE TABLE IF NOT EXISTS public.survey (
    id_survey integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_survey text NOT NULL,
    description text,
    date_create timestamp without time zone NOT NULL DEFAULT NOW(),
    date_open timestamp without time zone NOT NULL,
    date_close timestamp without time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS public.organization_survey (
    organization_id integer NOT NULL,
    id_survey integer NOT NULL,
    extended_until timestamp without time zone,
    CONSTRAINT organization_survey_pkey PRIMARY KEY (organization_id, id_survey),
    CONSTRAINT organization_survey_organization_id_fkey
        FOREIGN KEY (organization_id) REFERENCES public.organization (organization_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.app_user (
    id_user integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id integer,
    name_user text NOT NULL,
    full_name text NOT NULL,
    name_role text NOT NULL,
    hash_password text NOT NULL,
    email text,
    key_csp text,
    date_begin timestamp without time zone DEFAULT NOW(),
    date_end timestamp without time zone,
    CONSTRAINT app_user_name_user_key UNIQUE (name_user),
    CONSTRAINT chk_app_user_name_role CHECK (name_role IN ('admin', 'user')),
    CONSTRAINT app_user_organization_id_fkey
        FOREIGN KEY (organization_id) REFERENCES public.organization (organization_id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.answer (
    id_answer integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id integer NOT NULL,
    id_survey integer NOT NULL,
    csp text,
    completion_date timestamp without time zone,
    create_date_survey timestamp without time zone,
    CONSTRAINT answer_organization_id_fkey
        FOREIGN KEY (organization_id) REFERENCES public.organization (organization_id) ON DELETE RESTRICT,
    CONSTRAINT answer_organization_survey_key UNIQUE (organization_id, id_survey),
    CONSTRAINT answer_id_survey_fkey
        FOREIGN KEY (id_survey) REFERENCES public.survey (id_survey) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.survey_question (
    id_question integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_survey integer NOT NULL,
    question_order integer NOT NULL,
    question_text text NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT survey_question_id_survey_fkey
        FOREIGN KEY (id_survey) REFERENCES public.survey (id_survey) ON DELETE CASCADE,
    CONSTRAINT survey_question_id_survey_question_order_key
        UNIQUE (id_survey, question_order)
);

CREATE TABLE IF NOT EXISTS public.answer_item (
    id_item integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_answer integer NOT NULL,
    question_order integer NOT NULL,
    question_text text NOT NULL,
    rating integer,
    comment text,
    CONSTRAINT answer_item_id_answer_fkey
        FOREIGN KEY (id_answer) REFERENCES public.answer (id_answer) ON DELETE CASCADE,
    CONSTRAINT answer_item_id_answer_question_order_key
        UNIQUE (id_answer, question_order),
    CONSTRAINT chk_answer_item_rating
        CHECK (rating IS NULL OR (rating >= 1 AND rating <= 5))
);

CREATE TABLE IF NOT EXISTS public.app_user_l (
    id_audit bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation text NOT NULL,
    changed_at timestamp without time zone NOT NULL DEFAULT NOW(),
    changed_by_user_id integer,
    record_pk jsonb NOT NULL,
    row_data jsonb NOT NULL
);

CREATE TABLE IF NOT EXISTS public.organization_l (
    id_audit bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation text NOT NULL,
    changed_at timestamp without time zone NOT NULL DEFAULT NOW(),
    changed_by_user_id integer,
    record_pk jsonb NOT NULL,
    row_data jsonb NOT NULL
);

CREATE TABLE IF NOT EXISTS public.survey_l (
    id_audit bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation text NOT NULL,
    changed_at timestamp without time zone NOT NULL DEFAULT NOW(),
    changed_by_user_id integer,
    record_pk jsonb NOT NULL,
    row_data jsonb NOT NULL
);

CREATE TABLE IF NOT EXISTS public.answer_l (
    id_audit bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation text NOT NULL,
    changed_at timestamp without time zone NOT NULL DEFAULT NOW(),
    changed_by_user_id integer,
    record_pk jsonb NOT NULL,
    row_data jsonb NOT NULL
);

CREATE TABLE IF NOT EXISTS public.organization_survey_l (
    id_audit bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation text NOT NULL,
    changed_at timestamp without time zone NOT NULL DEFAULT NOW(),
    changed_by_user_id integer,
    record_pk jsonb NOT NULL,
    row_data jsonb NOT NULL
);

CREATE OR REPLACE FUNCTION public.audit_current_user_id()
RETURNS integer
LANGUAGE plpgsql
AS $$
DECLARE
    raw_value text;
BEGIN
    raw_value := current_setting('app.current_user_id', true);

    IF raw_value IS NULL OR BTRIM(raw_value) = '' THEN
        RETURN NULL;
    END IF;

    RETURN raw_value::integer;
EXCEPTION
    WHEN OTHERS THEN
        RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION public.write_crud_audit()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    source_row jsonb;
    record_pk jsonb := '{}'::jsonb;
    pk_name text;
    changed_by_user_id integer;
BEGIN
    source_row := CASE
        WHEN TG_OP = 'DELETE' THEN to_jsonb(OLD)
        ELSE to_jsonb(NEW)
    END;

    changed_by_user_id := public.audit_current_user_id();

    FOREACH pk_name IN ARRAY TG_ARGV LOOP
        record_pk := record_pk || jsonb_build_object(pk_name, source_row -> pk_name);
    END LOOP;

    EXECUTE format(
        'INSERT INTO public.%I_l (operation, changed_at, changed_by_user_id, record_pk, row_data)
         VALUES ($1, NOW(), $2, $3, $4)',
        TG_TABLE_NAME
    )
    USING TG_OP, changed_by_user_id, record_pk, source_row;

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;

    RETURN NEW;
END;
$$;

CREATE INDEX IF NOT EXISTS idx_organization_block ON public.organization (block);
CREATE INDEX IF NOT EXISTS idx_organization_date_end ON public.organization (date_end);
CREATE INDEX IF NOT EXISTS idx_organization_survey_id_survey ON public.organization_survey (id_survey);
CREATE INDEX IF NOT EXISTS idx_app_user_organization_id ON public.app_user (organization_id);
CREATE INDEX IF NOT EXISTS idx_app_user_date_end ON public.app_user (date_end);
CREATE INDEX IF NOT EXISTS idx_survey_date_close ON public.survey (date_close);
CREATE INDEX IF NOT EXISTS idx_survey_question_id_survey ON public.survey_question (id_survey, question_order);
CREATE INDEX IF NOT EXISTS idx_answer_id_survey ON public.answer (id_survey);
CREATE INDEX IF NOT EXISTS idx_answer_completion_date ON public.answer (completion_date);
CREATE INDEX IF NOT EXISTS idx_answer_item_id_answer ON public.answer_item (id_answer, question_order);
CREATE INDEX IF NOT EXISTS idx_app_user_l_changed_at ON public.app_user_l (changed_at DESC);
CREATE INDEX IF NOT EXISTS idx_organization_l_changed_at ON public.organization_l (changed_at DESC);
CREATE INDEX IF NOT EXISTS idx_survey_l_changed_at ON public.survey_l (changed_at DESC);
CREATE INDEX IF NOT EXISTS idx_answer_l_changed_at ON public.answer_l (changed_at DESC);
CREATE INDEX IF NOT EXISTS idx_organization_survey_l_changed_at ON public.organization_survey_l (changed_at DESC);
CREATE INDEX IF NOT EXISTS idx_app_user_l_record_pk ON public.app_user_l USING gin (record_pk);
CREATE INDEX IF NOT EXISTS idx_organization_l_record_pk ON public.organization_l USING gin (record_pk);
CREATE INDEX IF NOT EXISTS idx_survey_l_record_pk ON public.survey_l USING gin (record_pk);
CREATE INDEX IF NOT EXISTS idx_answer_l_record_pk ON public.answer_l USING gin (record_pk);
CREATE INDEX IF NOT EXISTS idx_organization_survey_l_record_pk ON public.organization_survey_l USING gin (record_pk);

DROP TRIGGER IF EXISTS trg_app_user_crud_audit ON public.app_user;
CREATE TRIGGER trg_app_user_crud_audit
    AFTER INSERT OR UPDATE OR DELETE ON public.app_user
    FOR EACH ROW
    EXECUTE FUNCTION public.write_crud_audit('id_user');

DROP TRIGGER IF EXISTS trg_organization_crud_audit ON public.organization;
CREATE TRIGGER trg_organization_crud_audit
    AFTER INSERT OR UPDATE OR DELETE ON public.organization
    FOR EACH ROW
    EXECUTE FUNCTION public.write_crud_audit('organization_id');

DROP TRIGGER IF EXISTS trg_survey_crud_audit ON public.survey;
CREATE TRIGGER trg_survey_crud_audit
    AFTER INSERT OR UPDATE OR DELETE ON public.survey
    FOR EACH ROW
    EXECUTE FUNCTION public.write_crud_audit('id_survey');

DROP TRIGGER IF EXISTS trg_answer_crud_audit ON public.answer;
CREATE TRIGGER trg_answer_crud_audit
    AFTER INSERT OR UPDATE OR DELETE ON public.answer
    FOR EACH ROW
    EXECUTE FUNCTION public.write_crud_audit('id_answer');

DROP TRIGGER IF EXISTS trg_organization_survey_crud_audit ON public.organization_survey;
CREATE TRIGGER trg_organization_survey_crud_audit
    AFTER INSERT OR UPDATE OR DELETE ON public.organization_survey
    FOR EACH ROW
    EXECUTE FUNCTION public.write_crud_audit('organization_id', 'id_survey');

COMMIT;
