BEGIN;

-- Reconstructed from application code because the repository does not contain
-- migrations or a database dump. This schema aims to match the SQL used by the
-- controllers closely enough to boot the app and continue manual recovery.

CREATE TABLE IF NOT EXISTS public.omsu (
    id_omsu integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_omsu text NOT NULL,
    date_begin date,
    date_end date,
    block boolean NOT NULL DEFAULT false,
    email text
);

CREATE TABLE IF NOT EXISTS public.omsu_surveys (
    id_omsu integer NOT NULL,
    id_survey integer NOT NULL,
    CONSTRAINT omsu_surveys_pkey PRIMARY KEY (id_omsu, id_survey),
    CONSTRAINT omsu_surveys_id_omsu_fkey
        FOREIGN KEY (id_omsu) REFERENCES public.omsu (id_omsu) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.users (
    id_user integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_omsu integer,
    name_user text NOT NULL,
    full_name text NOT NULL,
    name_role text NOT NULL,
    hash_password text NOT NULL,
    email text,
    key_csp text,
    date_begin timestamp without time zone DEFAULT NOW(),
    date_end timestamp without time zone,
    CONSTRAINT users_name_user_key UNIQUE (name_user),
    CONSTRAINT chk_users_name_role CHECK (name_role IN ('admin', 'user')),
    CONSTRAINT users_id_omsu_fkey
        FOREIGN KEY (id_omsu) REFERENCES public.omsu (id_omsu) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.surveys (
    id_survey integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_survey text NOT NULL,
    description text,
    date_create timestamp without time zone NOT NULL DEFAULT NOW(),
    date_open timestamp without time zone NOT NULL,
    date_close timestamp without time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS public.survey_questions (
    id_question integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_survey integer NOT NULL,
    question_order integer NOT NULL,
    question_text text NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_survey_questions_survey
        FOREIGN KEY (id_survey) REFERENCES public.surveys (id_survey) ON DELETE CASCADE,
    CONSTRAINT uq_survey_questions_order
        UNIQUE (id_survey, question_order)
);

CREATE TABLE IF NOT EXISTS public.history_surveys (
    id_hsurvey integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_survey integer NOT NULL,
    date_begin timestamp without time zone NOT NULL,
    date_end timestamp without time zone NOT NULL,
    csp text,
    id_user integer,
    name_survey text NOT NULL,
    description text,
    CONSTRAINT history_surveys_id_survey_key UNIQUE (id_survey)
);

CREATE TABLE IF NOT EXISTS public.history_survey_questions (
    id_history_question integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_survey integer NOT NULL,
    question_order integer NOT NULL,
    question_text text NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_history_survey_questions_order
        UNIQUE (id_survey, question_order)
);

CREATE TABLE IF NOT EXISTS public.history_answer (
    id_answer integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_omsu integer NOT NULL,
    id_survey integer NOT NULL,
    csp text,
    completion_date timestamp without time zone,
    create_date_survey timestamp without time zone,
    CONSTRAINT history_answer_id_omsu_fkey
        FOREIGN KEY (id_omsu) REFERENCES public.omsu (id_omsu) ON DELETE RESTRICT,
    CONSTRAINT history_answer_omsu_survey_key UNIQUE (id_omsu, id_survey)
);

CREATE TABLE IF NOT EXISTS public.history_answer_items (
    id_item integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_answer integer NOT NULL,
    question_order integer NOT NULL,
    question_text text NOT NULL,
    rating integer,
    comment text,
    CONSTRAINT fk_history_answer_items_answer
        FOREIGN KEY (id_answer) REFERENCES public.history_answer (id_answer) ON DELETE CASCADE,
    CONSTRAINT uq_history_answer_items_order
        UNIQUE (id_answer, question_order),
    CONSTRAINT chk_history_answer_items_rating
        CHECK (rating IS NULL OR (rating >= 1 AND rating <= 5))
);

CREATE TABLE IF NOT EXISTS public.access_extensions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_survey integer NOT NULL,
    id_omsu integer NOT NULL,
    new_end_date timestamp without time zone NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT access_extensions_id_omsu_fkey
        FOREIGN KEY (id_omsu) REFERENCES public.omsu (id_omsu) ON DELETE RESTRICT,
    CONSTRAINT access_extensions_id_survey_fkey
        FOREIGN KEY (id_survey) REFERENCES public.surveys (id_survey) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.logs (
    id_log integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_user integer NOT NULL DEFAULT 0,
    id_target integer,
    target_type text NOT NULL,
    event_type text NOT NULL,
    date timestamp without time zone NOT NULL DEFAULT NOW(),
    extra_data jsonb,
    description text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.users_l (
    id_audit bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation text NOT NULL,
    changed_at timestamp without time zone NOT NULL DEFAULT NOW(),
    changed_by_user_id integer,
    record_pk jsonb NOT NULL,
    row_data jsonb NOT NULL
);

CREATE TABLE IF NOT EXISTS public.omsu_l (
    id_audit bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation text NOT NULL,
    changed_at timestamp without time zone NOT NULL DEFAULT NOW(),
    changed_by_user_id integer,
    record_pk jsonb NOT NULL,
    row_data jsonb NOT NULL
);

CREATE TABLE IF NOT EXISTS public.surveys_l (
    id_audit bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation text NOT NULL,
    changed_at timestamp without time zone NOT NULL DEFAULT NOW(),
    changed_by_user_id integer,
    record_pk jsonb NOT NULL,
    row_data jsonb NOT NULL
);

CREATE TABLE IF NOT EXISTS public.history_answer_l (
    id_audit bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation text NOT NULL,
    changed_at timestamp without time zone NOT NULL DEFAULT NOW(),
    changed_by_user_id integer,
    record_pk jsonb NOT NULL,
    row_data jsonb NOT NULL
);

CREATE TABLE IF NOT EXISTS public.omsu_surveys_l (
    id_audit bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation text NOT NULL,
    changed_at timestamp without time zone NOT NULL DEFAULT NOW(),
    changed_by_user_id integer,
    record_pk jsonb NOT NULL,
    row_data jsonb NOT NULL
);

CREATE OR REPLACE FUNCTION public.audit_current_user_id()
RETURNS integer
LANGUAGE plpgsql
AS $$
DECLARE
    raw_value text;
BEGIN
    raw_value := current_setting('app.current_user_id', true);

    IF raw_value IS NULL OR BTRIM(raw_value) = '' THEN
        RETURN NULL;
    END IF;

    RETURN raw_value::integer;
EXCEPTION
    WHEN OTHERS THEN
        RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION public.write_crud_audit()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    source_row jsonb;
    record_pk jsonb := '{}'::jsonb;
    pk_name text;
    changed_by_user_id integer;
BEGIN
    source_row := CASE
        WHEN TG_OP = 'DELETE' THEN to_jsonb(OLD)
        ELSE to_jsonb(NEW)
    END;

    changed_by_user_id := public.audit_current_user_id();

    FOREACH pk_name IN ARRAY TG_ARGV LOOP
        record_pk := record_pk || jsonb_build_object(pk_name, source_row -> pk_name);
    END LOOP;

    EXECUTE format(
        'INSERT INTO public.%I_l (operation, changed_at, changed_by_user_id, record_pk, row_data)
         VALUES ($1, NOW(), $2, $3, $4)',
        TG_TABLE_NAME
    )
    USING TG_OP, changed_by_user_id, record_pk, source_row;

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;

    RETURN NEW;
END;
$$;

-- SurveyController.LogSurveyCreation() writes into `public.log` instead of
-- `public.logs`. A simple updatable view keeps that code path working.
DROP VIEW IF EXISTS public.log;
CREATE VIEW public.log AS
SELECT
    id_log,
    id_user,
    id_target,
    target_type,
    event_type,
    date,
    extra_data,
    description
FROM public.logs;

CREATE INDEX IF NOT EXISTS idx_omsu_block ON public.omsu (block);
CREATE INDEX IF NOT EXISTS idx_omsu_date_end ON public.omsu (date_end);
CREATE INDEX IF NOT EXISTS idx_omsu_surveys_id_survey ON public.omsu_surveys (id_survey);
CREATE INDEX IF NOT EXISTS idx_users_id_omsu ON public.users (id_omsu);
CREATE INDEX IF NOT EXISTS idx_users_date_end ON public.users (date_end);
CREATE INDEX IF NOT EXISTS idx_surveys_date_close ON public.surveys (date_close);
CREATE INDEX IF NOT EXISTS idx_survey_questions_id_survey ON public.survey_questions (id_survey, question_order);
CREATE INDEX IF NOT EXISTS idx_history_survey_questions_id_survey ON public.history_survey_questions (id_survey, question_order);
CREATE INDEX IF NOT EXISTS idx_history_answer_id_survey ON public.history_answer (id_survey);
CREATE INDEX IF NOT EXISTS idx_history_answer_completion_date ON public.history_answer (completion_date);
CREATE INDEX IF NOT EXISTS idx_history_answer_items_id_answer ON public.history_answer_items (id_answer, question_order);
CREATE INDEX IF NOT EXISTS idx_access_extensions_lookup ON public.access_extensions (id_survey, id_omsu);
CREATE INDEX IF NOT EXISTS idx_logs_date ON public.logs (date);
CREATE INDEX IF NOT EXISTS idx_logs_event_type ON public.logs (event_type);
CREATE INDEX IF NOT EXISTS idx_users_l_changed_at ON public.users_l (changed_at DESC);
CREATE INDEX IF NOT EXISTS idx_omsu_l_changed_at ON public.omsu_l (changed_at DESC);
CREATE INDEX IF NOT EXISTS idx_surveys_l_changed_at ON public.surveys_l (changed_at DESC);
CREATE INDEX IF NOT EXISTS idx_history_answer_l_changed_at ON public.history_answer_l (changed_at DESC);
CREATE INDEX IF NOT EXISTS idx_omsu_surveys_l_changed_at ON public.omsu_surveys_l (changed_at DESC);
CREATE INDEX IF NOT EXISTS idx_users_l_record_pk ON public.users_l USING gin (record_pk);
CREATE INDEX IF NOT EXISTS idx_omsu_l_record_pk ON public.omsu_l USING gin (record_pk);
CREATE INDEX IF NOT EXISTS idx_surveys_l_record_pk ON public.surveys_l USING gin (record_pk);
CREATE INDEX IF NOT EXISTS idx_history_answer_l_record_pk ON public.history_answer_l USING gin (record_pk);
CREATE INDEX IF NOT EXISTS idx_omsu_surveys_l_record_pk ON public.omsu_surveys_l USING gin (record_pk);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'surveys'
          AND column_name = 'questions'
    ) THEN
        INSERT INTO public.survey_questions (id_survey, question_order, question_text)
        SELECT
            s.id_survey,
            CASE
                WHEN COALESCE(question.item ->> 'question_id', '') ~ '^[0-9]+$'
                    THEN (question.item ->> 'question_id')::integer
                ELSE question.ordinality::integer
            END AS question_order,
            COALESCE(
                NULLIF(BTRIM(question.item ->> 'text'), ''),
                'Вопрос ' || question.ordinality::text
            ) AS question_text
        FROM public.surveys s
        CROSS JOIN LATERAL jsonb_array_elements(
            CASE
                WHEN jsonb_typeof(s.questions -> 'questions') = 'array' THEN s.questions -> 'questions'
                WHEN jsonb_typeof(s.questions) = 'array' THEN s.questions
                ELSE '[]'::jsonb
            END
        ) WITH ORDINALITY AS question(item, ordinality)
        ON CONFLICT (id_survey, question_order) DO UPDATE
        SET question_text = EXCLUDED.question_text;
    END IF;
END $$;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'history_surveys'
          AND column_name = 'file_questions'
    ) THEN
        INSERT INTO public.history_survey_questions (id_survey, question_order, question_text)
        SELECT
            hs.id_survey,
            CASE
                WHEN COALESCE(question.item ->> 'question_id', '') ~ '^[0-9]+$'
                    THEN (question.item ->> 'question_id')::integer
                ELSE question.ordinality::integer
            END AS question_order,
            COALESCE(
                NULLIF(BTRIM(question.item ->> 'text'), ''),
                'Вопрос ' || question.ordinality::text
            ) AS question_text
        FROM public.history_surveys hs
        CROSS JOIN LATERAL jsonb_array_elements(
            CASE
                WHEN jsonb_typeof(hs.file_questions -> 'questions') = 'array' THEN hs.file_questions -> 'questions'
                WHEN jsonb_typeof(hs.file_questions) = 'array' THEN hs.file_questions
                ELSE '[]'::jsonb
            END
        ) WITH ORDINALITY AS question(item, ordinality)
        ON CONFLICT (id_survey, question_order) DO UPDATE
        SET question_text = EXCLUDED.question_text;
    END IF;
END $$;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'history_answer'
          AND column_name = 'answers'
    ) THEN
        INSERT INTO public.history_answer_items (id_answer, question_order, question_text, rating, comment)
        SELECT
            ha.id_answer,
            CASE
                WHEN COALESCE(answer_item.item ->> 'question_id', '') ~ '^[0-9]+$'
                    THEN (answer_item.item ->> 'question_id')::integer
                ELSE answer_item.ordinality::integer
            END AS question_order,
            COALESCE(
                NULLIF(BTRIM(COALESCE(answer_item.item ->> 'question_text', answer_item.item ->> 'text')), ''),
                'Вопрос ' || answer_item.ordinality::text
            ) AS question_text,
            CASE
                WHEN COALESCE(answer_item.item ->> 'rating', '') ~ '^[0-9]+$'
                    THEN (answer_item.item ->> 'rating')::integer
                ELSE NULL
            END AS rating,
            NULLIF(answer_item.item ->> 'comment', '') AS comment
        FROM public.history_answer ha
        CROSS JOIN LATERAL jsonb_array_elements(
            CASE
                WHEN jsonb_typeof(ha.answers) = 'array' THEN ha.answers
                ELSE '[]'::jsonb
            END
        ) WITH ORDINALITY AS answer_item(item, ordinality)
        ON CONFLICT (id_answer, question_order) DO UPDATE
        SET question_text = EXCLUDED.question_text,
            rating = EXCLUDED.rating,
            comment = EXCLUDED.comment;
    END IF;
END $$;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'surveys'
          AND column_name = 'questions'
    ) THEN
        ALTER TABLE public.surveys DROP COLUMN questions;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'history_surveys'
          AND column_name = 'file_questions'
    ) THEN
        ALTER TABLE public.history_surveys DROP COLUMN file_questions;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'history_answer'
          AND column_name = 'answers'
    ) THEN
        ALTER TABLE public.history_answer DROP COLUMN answers;
    END IF;
END $$;

DROP TRIGGER IF EXISTS trg_users_crud_audit ON public.users;
CREATE TRIGGER trg_users_crud_audit
    AFTER INSERT OR UPDATE OR DELETE ON public.users
    FOR EACH ROW
    EXECUTE FUNCTION public.write_crud_audit('id_user');

DROP TRIGGER IF EXISTS trg_omsu_crud_audit ON public.omsu;
CREATE TRIGGER trg_omsu_crud_audit
    AFTER INSERT OR UPDATE OR DELETE ON public.omsu
    FOR EACH ROW
    EXECUTE FUNCTION public.write_crud_audit('id_omsu');

DROP TRIGGER IF EXISTS trg_surveys_crud_audit ON public.surveys;
CREATE TRIGGER trg_surveys_crud_audit
    AFTER INSERT OR UPDATE OR DELETE ON public.surveys
    FOR EACH ROW
    EXECUTE FUNCTION public.write_crud_audit('id_survey');

DROP TRIGGER IF EXISTS trg_history_answer_crud_audit ON public.history_answer;
CREATE TRIGGER trg_history_answer_crud_audit
    AFTER INSERT OR UPDATE OR DELETE ON public.history_answer
    FOR EACH ROW
    EXECUTE FUNCTION public.write_crud_audit('id_answer');

DROP TRIGGER IF EXISTS trg_omsu_surveys_crud_audit ON public.omsu_surveys;
CREATE TRIGGER trg_omsu_surveys_crud_audit
    AFTER INSERT OR UPDATE OR DELETE ON public.omsu_surveys
    FOR EACH ROW
    EXECUTE FUNCTION public.write_crud_audit('id_omsu', 'id_survey');

COMMIT;
