BEGIN;

-- Reconstructed from application code because the repository does not contain
-- migrations or a database dump. This schema aims to match the SQL used by the
-- controllers closely enough to boot the app and continue manual recovery.

CREATE TABLE IF NOT EXISTS public.omsu (
    id_omsu integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_omsu text NOT NULL,
    date_begin date,
    date_end date,
    block boolean NOT NULL DEFAULT false,
    email text
);

CREATE TABLE IF NOT EXISTS public.omsu_surveys (
    id_omsu integer NOT NULL,
    id_survey integer NOT NULL,
    CONSTRAINT omsu_surveys_pkey PRIMARY KEY (id_omsu, id_survey),
    CONSTRAINT omsu_surveys_id_omsu_fkey
        FOREIGN KEY (id_omsu) REFERENCES public.omsu (id_omsu) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.users (
    id_user integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_omsu integer,
    name_user text NOT NULL,
    full_name text NOT NULL,
    name_role text NOT NULL,
    hash_password text NOT NULL,
    email text,
    key_csp text,
    date_begin timestamp without time zone DEFAULT NOW(),
    date_end timestamp without time zone,
    CONSTRAINT users_name_user_key UNIQUE (name_user),
    CONSTRAINT chk_users_name_role CHECK (name_role IN ('Админ', 'user')),
    CONSTRAINT users_id_omsu_fkey
        FOREIGN KEY (id_omsu) REFERENCES public.omsu (id_omsu) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.surveys (
    id_survey integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_survey text NOT NULL,
    description text,
    questions jsonb,
    date_create timestamp without time zone NOT NULL DEFAULT NOW(),
    date_open timestamp without time zone NOT NULL,
    date_close timestamp without time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS public.history_surveys (
    id_hsurvey integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_survey integer NOT NULL,
    date_begin timestamp without time zone NOT NULL,
    date_end timestamp without time zone NOT NULL,
    csp text,
    id_user integer,
    name_survey text NOT NULL,
    description text,
    file_questions jsonb,
    CONSTRAINT history_surveys_id_survey_key UNIQUE (id_survey)
);

CREATE TABLE IF NOT EXISTS public.history_answer (
    id_answer integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_omsu integer NOT NULL,
    id_survey integer NOT NULL,
    csp text,
    completion_date timestamp without time zone,
    create_date_survey timestamp without time zone,
    answers jsonb NOT NULL DEFAULT '[]'::jsonb,
    CONSTRAINT history_answer_id_omsu_fkey
        FOREIGN KEY (id_omsu) REFERENCES public.omsu (id_omsu) ON DELETE RESTRICT,
    CONSTRAINT history_answer_omsu_survey_key UNIQUE (id_omsu, id_survey)
);

CREATE TABLE IF NOT EXISTS public.access_extensions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_survey integer NOT NULL,
    id_omsu integer NOT NULL,
    new_end_date timestamp without time zone NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT access_extensions_id_omsu_fkey
        FOREIGN KEY (id_omsu) REFERENCES public.omsu (id_omsu) ON DELETE RESTRICT,
    CONSTRAINT access_extensions_id_survey_fkey
        FOREIGN KEY (id_survey) REFERENCES public.surveys (id_survey) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.logs (
    id_log integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_user integer NOT NULL DEFAULT 0,
    id_target integer,
    target_type text NOT NULL,
    event_type text NOT NULL,
    date timestamp without time zone NOT NULL DEFAULT NOW(),
    extra_data jsonb,
    description text NOT NULL
);

-- SurveyController.LogSurveyCreation() writes into `public.log` instead of
-- `public.logs`. A simple updatable view keeps that code path working.
DROP VIEW IF EXISTS public.log;
CREATE VIEW public.log AS
SELECT
    id_log,
    id_user,
    id_target,
    target_type,
    event_type,
    date,
    extra_data,
    description
FROM public.logs;

CREATE INDEX IF NOT EXISTS idx_omsu_block ON public.omsu (block);
CREATE INDEX IF NOT EXISTS idx_omsu_date_end ON public.omsu (date_end);
CREATE INDEX IF NOT EXISTS idx_omsu_surveys_id_survey ON public.omsu_surveys (id_survey);
CREATE INDEX IF NOT EXISTS idx_users_id_omsu ON public.users (id_omsu);
CREATE INDEX IF NOT EXISTS idx_users_date_end ON public.users (date_end);
CREATE INDEX IF NOT EXISTS idx_surveys_date_close ON public.surveys (date_close);
CREATE INDEX IF NOT EXISTS idx_history_answer_id_survey ON public.history_answer (id_survey);
CREATE INDEX IF NOT EXISTS idx_history_answer_completion_date ON public.history_answer (completion_date);
CREATE INDEX IF NOT EXISTS idx_access_extensions_lookup ON public.access_extensions (id_survey, id_omsu);
CREATE INDEX IF NOT EXISTS idx_logs_date ON public.logs (date);
CREATE INDEX IF NOT EXISTS idx_logs_event_type ON public.logs (event_type);

COMMIT;
