using Npgsql;

namespace main_project.Infrastructure.Database;

public static class CrudAuditBootstrapper
{
    private static readonly object SyncRoot = new();
    private static bool _initialized;

    public static void EnsureInitialized(NpgsqlConnection connection)
    {
        if (_initialized)
        {
            return;
        }

        lock (SyncRoot)
        {
            if (_initialized)
            {
                return;
            }

            using var command = new NpgsqlCommand(
                """
                CREATE OR REPLACE FUNCTION public.audit_current_user_id()
                RETURNS integer
                LANGUAGE plpgsql
                AS $$
                DECLARE
                    raw_value text;
                BEGIN
                    raw_value := current_setting('app.current_user_id', true);

                    IF raw_value IS NULL OR BTRIM(raw_value) = '' THEN
                        RETURN NULL;
                    END IF;

                    RETURN raw_value::integer;
                EXCEPTION
                    WHEN OTHERS THEN
                        RETURN NULL;
                END;
                $$;

                CREATE OR REPLACE FUNCTION public.write_crud_audit()
                RETURNS trigger
                LANGUAGE plpgsql
                AS $$
                DECLARE
                    source_row jsonb;
                    record_pk jsonb := '{}'::jsonb;
                    pk_name text;
                    changed_by_user_id integer;
                BEGIN
                    source_row := CASE
                        WHEN TG_OP = 'DELETE' THEN to_jsonb(OLD)
                        ELSE to_jsonb(NEW)
                    END;

                    changed_by_user_id := public.audit_current_user_id();

                    FOREACH pk_name IN ARRAY TG_ARGV LOOP
                        record_pk := record_pk || jsonb_build_object(pk_name, source_row -> pk_name);
                    END LOOP;

                    EXECUTE format(
                        'INSERT INTO public.%I_l (operation, changed_at, changed_by_user_id, record_pk, row_data)
                         VALUES ($1, NOW(), $2, $3, $4)',
                        TG_TABLE_NAME
                    )
                    USING TG_OP, changed_by_user_id, record_pk, source_row;

                    IF TG_OP = 'DELETE' THEN
                        RETURN OLD;
                    END IF;

                    RETURN NEW;
                END;
                $$;

                DO $$
                BEGIN
                    IF to_regclass('public.history_answer_l') IS NOT NULL
                       AND to_regclass('public.answer_l') IS NULL THEN
                        ALTER TABLE public.history_answer_l RENAME TO answer_l;
                    END IF;

                    IF to_regclass('public.history_answer_l_id_audit_seq') IS NOT NULL
                       AND to_regclass('public.answer_l_id_audit_seq') IS NULL THEN
                        ALTER SEQUENCE public.history_answer_l_id_audit_seq RENAME TO answer_l_id_audit_seq;
                    END IF;

                    IF to_regclass('public.idx_history_answer_l_changed_at') IS NOT NULL
                       AND to_regclass('public.idx_answer_l_changed_at') IS NULL THEN
                        ALTER INDEX public.idx_history_answer_l_changed_at RENAME TO idx_answer_l_changed_at;
                    END IF;

                    IF to_regclass('public.idx_history_answer_l_record_pk') IS NOT NULL
                       AND to_regclass('public.idx_answer_l_record_pk') IS NULL THEN
                        ALTER INDEX public.idx_history_answer_l_record_pk RENAME TO idx_answer_l_record_pk;
                    END IF;
                END $$;

                CREATE TABLE IF NOT EXISTS public.app_user_l (
                    id_audit bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    operation text NOT NULL,
                    changed_at timestamp without time zone NOT NULL DEFAULT NOW(),
                    changed_by_user_id integer,
                    record_pk jsonb NOT NULL,
                    row_data jsonb NOT NULL
                );

                CREATE TABLE IF NOT EXISTS public.organization_l (
                    id_audit bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    operation text NOT NULL,
                    changed_at timestamp without time zone NOT NULL DEFAULT NOW(),
                    changed_by_user_id integer,
                    record_pk jsonb NOT NULL,
                    row_data jsonb NOT NULL
                );

                CREATE TABLE IF NOT EXISTS public.survey_l (
                    id_audit bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    operation text NOT NULL,
                    changed_at timestamp without time zone NOT NULL DEFAULT NOW(),
                    changed_by_user_id integer,
                    record_pk jsonb NOT NULL,
                    row_data jsonb NOT NULL
                );

                CREATE TABLE IF NOT EXISTS public.answer_l (
                    id_audit bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    operation text NOT NULL,
                    changed_at timestamp without time zone NOT NULL DEFAULT NOW(),
                    changed_by_user_id integer,
                    record_pk jsonb NOT NULL,
                    row_data jsonb NOT NULL
                );

                CREATE TABLE IF NOT EXISTS public.organization_survey_l (
                    id_audit bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    operation text NOT NULL,
                    changed_at timestamp without time zone NOT NULL DEFAULT NOW(),
                    changed_by_user_id integer,
                    record_pk jsonb NOT NULL,
                    row_data jsonb NOT NULL
                );

                CREATE INDEX IF NOT EXISTS idx_app_user_l_changed_at ON public.app_user_l (changed_at DESC);
                CREATE INDEX IF NOT EXISTS idx_organization_l_changed_at ON public.organization_l (changed_at DESC);
                CREATE INDEX IF NOT EXISTS idx_survey_l_changed_at ON public.survey_l (changed_at DESC);
                CREATE INDEX IF NOT EXISTS idx_answer_l_changed_at ON public.answer_l (changed_at DESC);
                CREATE INDEX IF NOT EXISTS idx_organization_survey_l_changed_at ON public.organization_survey_l (changed_at DESC);

                CREATE INDEX IF NOT EXISTS idx_app_user_l_record_pk ON public.app_user_l USING gin (record_pk);
                CREATE INDEX IF NOT EXISTS idx_organization_l_record_pk ON public.organization_l USING gin (record_pk);
                CREATE INDEX IF NOT EXISTS idx_survey_l_record_pk ON public.survey_l USING gin (record_pk);
                CREATE INDEX IF NOT EXISTS idx_answer_l_record_pk ON public.answer_l USING gin (record_pk);
                CREATE INDEX IF NOT EXISTS idx_organization_survey_l_record_pk ON public.organization_survey_l USING gin (record_pk);

                DROP TRIGGER IF EXISTS trg_app_user_crud_audit ON public.app_user;
                DROP TRIGGER IF EXISTS trg_users_crud_audit ON public.app_user;
                CREATE TRIGGER trg_app_user_crud_audit
                    AFTER INSERT OR UPDATE OR DELETE ON public.app_user
                    FOR EACH ROW
                    EXECUTE FUNCTION public.write_crud_audit('id_user');

                DROP TRIGGER IF EXISTS trg_organization_crud_audit ON public.organization;
                DROP TRIGGER IF EXISTS trg_omsu_crud_audit ON public.organization;
                DROP TRIGGER IF EXISTS trg_organizations_crud_audit ON public.organization;
                CREATE TRIGGER trg_organization_crud_audit
                    AFTER INSERT OR UPDATE OR DELETE ON public.organization
                    FOR EACH ROW
                    EXECUTE FUNCTION public.write_crud_audit('organization_id');

                DROP TRIGGER IF EXISTS trg_survey_crud_audit ON public.survey;
                DROP TRIGGER IF EXISTS trg_surveys_crud_audit ON public.survey;
                CREATE TRIGGER trg_survey_crud_audit
                    AFTER INSERT OR UPDATE OR DELETE ON public.survey
                    FOR EACH ROW
                    EXECUTE FUNCTION public.write_crud_audit('id_survey');

                DROP TRIGGER IF EXISTS trg_history_answer_crud_audit ON public.answer;
                DROP TRIGGER IF EXISTS trg_answer_crud_audit ON public.answer;
                CREATE TRIGGER trg_answer_crud_audit
                    AFTER INSERT OR UPDATE OR DELETE ON public.answer
                    FOR EACH ROW
                    EXECUTE FUNCTION public.write_crud_audit('id_answer');

                DROP TRIGGER IF EXISTS trg_organization_survey_crud_audit ON public.organization_survey;
                DROP TRIGGER IF EXISTS trg_omsu_surveys_crud_audit ON public.organization_survey;
                DROP TRIGGER IF EXISTS trg_organization_surveys_crud_audit ON public.organization_survey;
                CREATE TRIGGER trg_organization_survey_crud_audit
                    AFTER INSERT OR UPDATE OR DELETE ON public.organization_survey
                    FOR EACH ROW
                    EXECUTE FUNCTION public.write_crud_audit('organization_id', 'id_survey');
                """,
                connection);

            command.ExecuteNonQuery();
            _initialized = true;
        }
    }
}
