using Npgsql;

namespace main_project.Infrastructure.Database;

public static class CrudAuditBootstrapper
{
    private static readonly object SyncRoot = new();
    private static bool _initialized;

    public static void EnsureInitialized(NpgsqlConnection connection)
    {
        if (_initialized)
        {
            return;
        }

        lock (SyncRoot)
        {
            if (_initialized)
            {
                return;
            }

            using var command = new NpgsqlCommand(
                """
                CREATE OR REPLACE FUNCTION public.audit_current_user_id()
                RETURNS integer
                LANGUAGE plpgsql
                AS $$
                DECLARE
                    raw_value text;
                BEGIN
                    raw_value := current_setting('app.current_user_id', true);

                    IF raw_value IS NULL OR BTRIM(raw_value) = '' THEN
                        RETURN NULL;
                    END IF;

                    RETURN raw_value::integer;
                EXCEPTION
                    WHEN OTHERS THEN
                        RETURN NULL;
                END;
                $$;

                CREATE OR REPLACE FUNCTION public.write_crud_audit()
                RETURNS trigger
                LANGUAGE plpgsql
                AS $$
                DECLARE
                    source_row jsonb;
                    record_pk jsonb := '{}'::jsonb;
                    pk_name text;
                    changed_by_user_id integer;
                BEGIN
                    source_row := CASE
                        WHEN TG_OP = 'DELETE' THEN to_jsonb(OLD)
                        ELSE to_jsonb(NEW)
                    END;

                    changed_by_user_id := public.audit_current_user_id();

                    FOREACH pk_name IN ARRAY TG_ARGV LOOP
                        record_pk := record_pk || jsonb_build_object(pk_name, source_row -> pk_name);
                    END LOOP;

                    EXECUTE format(
                        'INSERT INTO public.%I_l (operation, changed_at, changed_by_user_id, record_pk, row_data)
                         VALUES ($1, NOW(), $2, $3, $4)',
                        TG_TABLE_NAME
                    )
                    USING TG_OP, changed_by_user_id, record_pk, source_row;

                    IF TG_OP = 'DELETE' THEN
                        RETURN OLD;
                    END IF;

                    RETURN NEW;
                END;
                $$;

                CREATE TABLE IF NOT EXISTS public.users_l (
                    id_audit bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    operation text NOT NULL,
                    changed_at timestamp without time zone NOT NULL DEFAULT NOW(),
                    changed_by_user_id integer,
                    record_pk jsonb NOT NULL,
                    row_data jsonb NOT NULL
                );

                CREATE TABLE IF NOT EXISTS public.omsu_l (
                    id_audit bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    operation text NOT NULL,
                    changed_at timestamp without time zone NOT NULL DEFAULT NOW(),
                    changed_by_user_id integer,
                    record_pk jsonb NOT NULL,
                    row_data jsonb NOT NULL
                );

                CREATE TABLE IF NOT EXISTS public.surveys_l (
                    id_audit bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    operation text NOT NULL,
                    changed_at timestamp without time zone NOT NULL DEFAULT NOW(),
                    changed_by_user_id integer,
                    record_pk jsonb NOT NULL,
                    row_data jsonb NOT NULL
                );

                CREATE TABLE IF NOT EXISTS public.history_answer_l (
                    id_audit bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    operation text NOT NULL,
                    changed_at timestamp without time zone NOT NULL DEFAULT NOW(),
                    changed_by_user_id integer,
                    record_pk jsonb NOT NULL,
                    row_data jsonb NOT NULL
                );

                CREATE TABLE IF NOT EXISTS public.omsu_surveys_l (
                    id_audit bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    operation text NOT NULL,
                    changed_at timestamp without time zone NOT NULL DEFAULT NOW(),
                    changed_by_user_id integer,
                    record_pk jsonb NOT NULL,
                    row_data jsonb NOT NULL
                );

                CREATE INDEX IF NOT EXISTS idx_users_l_changed_at ON public.users_l (changed_at DESC);
                CREATE INDEX IF NOT EXISTS idx_omsu_l_changed_at ON public.omsu_l (changed_at DESC);
                CREATE INDEX IF NOT EXISTS idx_surveys_l_changed_at ON public.surveys_l (changed_at DESC);
                CREATE INDEX IF NOT EXISTS idx_history_answer_l_changed_at ON public.history_answer_l (changed_at DESC);
                CREATE INDEX IF NOT EXISTS idx_omsu_surveys_l_changed_at ON public.omsu_surveys_l (changed_at DESC);

                CREATE INDEX IF NOT EXISTS idx_users_l_record_pk ON public.users_l USING gin (record_pk);
                CREATE INDEX IF NOT EXISTS idx_omsu_l_record_pk ON public.omsu_l USING gin (record_pk);
                CREATE INDEX IF NOT EXISTS idx_surveys_l_record_pk ON public.surveys_l USING gin (record_pk);
                CREATE INDEX IF NOT EXISTS idx_history_answer_l_record_pk ON public.history_answer_l USING gin (record_pk);
                CREATE INDEX IF NOT EXISTS idx_omsu_surveys_l_record_pk ON public.omsu_surveys_l USING gin (record_pk);

                DROP TRIGGER IF EXISTS trg_users_crud_audit ON public.users;
                CREATE TRIGGER trg_users_crud_audit
                    AFTER INSERT OR UPDATE OR DELETE ON public.users
                    FOR EACH ROW
                    EXECUTE FUNCTION public.write_crud_audit('id_user');

                DROP TRIGGER IF EXISTS trg_omsu_crud_audit ON public.omsu;
                CREATE TRIGGER trg_omsu_crud_audit
                    AFTER INSERT OR UPDATE OR DELETE ON public.omsu
                    FOR EACH ROW
                    EXECUTE FUNCTION public.write_crud_audit('id_omsu');

                DROP TRIGGER IF EXISTS trg_surveys_crud_audit ON public.surveys;
                CREATE TRIGGER trg_surveys_crud_audit
                    AFTER INSERT OR UPDATE OR DELETE ON public.surveys
                    FOR EACH ROW
                    EXECUTE FUNCTION public.write_crud_audit('id_survey');

                DROP TRIGGER IF EXISTS trg_history_answer_crud_audit ON public.history_answer;
                CREATE TRIGGER trg_history_answer_crud_audit
                    AFTER INSERT OR UPDATE OR DELETE ON public.history_answer
                    FOR EACH ROW
                    EXECUTE FUNCTION public.write_crud_audit('id_answer');

                DROP TRIGGER IF EXISTS trg_omsu_surveys_crud_audit ON public.omsu_surveys;
                CREATE TRIGGER trg_omsu_surveys_crud_audit
                    AFTER INSERT OR UPDATE OR DELETE ON public.omsu_surveys
                    FOR EACH ROW
                    EXECUTE FUNCTION public.write_crud_audit('id_omsu', 'id_survey');
                """,
                connection);

            command.ExecuteNonQuery();
            _initialized = true;
        }
    }
}
