using Npgsql;

namespace MainProject.Infrastructure.Database;

public static class SurveyNormalizationBootstrapper
{
    private static readonly object SyncRoot = new();
    private static bool _initialized;

    public static void EnsureInitialized(NpgsqlConnection connection)
    {
        if (_initialized)
        {
            return;
        }

        lock (SyncRoot)
        {
            if (_initialized)
            {
                return;
            }

            using var command = new NpgsqlCommand(
                """
                CREATE TABLE IF NOT EXISTS public.answer (
                    id_answer integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    organization_id integer NOT NULL,
                    id_survey integer NOT NULL,
                    csp text,
                    completion_date timestamp without time zone,
                    create_date_survey timestamp without time zone,
                    CONSTRAINT answer_organization_id_fkey
                        FOREIGN KEY (organization_id) REFERENCES public.organization (organization_id) ON DELETE RESTRICT,
                    CONSTRAINT answer_organization_survey_key
                        UNIQUE (organization_id, id_survey),
                    CONSTRAINT answer_id_survey_fkey
                        FOREIGN KEY (id_survey) REFERENCES public.survey (id_survey) ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS public.survey_question (
                    id_question integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    id_survey integer NOT NULL,
                    question_order integer NOT NULL,
                    question_text text NOT NULL,
                    created_at timestamp without time zone NOT NULL DEFAULT NOW(),
                    CONSTRAINT survey_question_id_survey_fkey
                        FOREIGN KEY (id_survey) REFERENCES public.survey (id_survey) ON DELETE CASCADE,
                    CONSTRAINT survey_question_id_survey_question_order_key
                        UNIQUE (id_survey, question_order)
                );

                CREATE TABLE IF NOT EXISTS public.answer_item (
                    id_item integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    id_answer integer NOT NULL,
                    question_order integer NOT NULL,
                    question_text text NOT NULL,
                    rating integer,
                    comment text,
                    CONSTRAINT answer_item_id_answer_fkey
                        FOREIGN KEY (id_answer) REFERENCES public.answer (id_answer) ON DELETE CASCADE,
                    CONSTRAINT answer_item_id_answer_question_order_key
                        UNIQUE (id_answer, question_order),
                    CONSTRAINT chk_answer_item_rating
                        CHECK (rating IS NULL OR (rating >= 1 AND rating <= 5))
                );

                ALTER TABLE public.organization_survey
                    ADD COLUMN IF NOT EXISTS extended_until timestamp without time zone;

                CREATE INDEX IF NOT EXISTS idx_survey_question_id_survey
                    ON public.survey_question (id_survey, question_order);

                CREATE INDEX IF NOT EXISTS idx_answer_id_survey
                    ON public.answer (id_survey);

                CREATE INDEX IF NOT EXISTS idx_answer_completion_date
                    ON public.answer (completion_date);

                CREATE INDEX IF NOT EXISTS idx_answer_item_id_answer
                    ON public.answer_item (id_answer, question_order);
                """,
                connection);

            command.ExecuteNonQuery();

            MigrateArchivedSurveys(connection);
            BackfillSurveyQuestions(connection);
            BackfillArchivedSurveyQuestions(connection);
            BackfillAnswerItems(connection);
            MigrateExtensions(connection);
            DropLegacyColumns(connection);
            DropLegacyTables(connection);

            _initialized = true;
        }
    }

    private static void MigrateArchivedSurveys(NpgsqlConnection connection)
    {
        if (!TableExists(connection, "history_survey"))
        {
            return;
        }

        using (var command = new NpgsqlCommand(
                   """
                   INSERT INTO public.survey (
                       id_survey,
                       name_survey,
                       description,
                       date_create,
                       date_open,
                       date_close
                   )
                   SELECT
                       hs.id_survey,
                       hs.name_survey,
                       hs.description,
                       COALESCE(hs.date_begin, NOW()),
                       hs.date_begin,
                       hs.date_end
                   FROM public.history_survey hs
                   ON CONFLICT (id_survey) DO NOTHING;
                   """,
                   connection))
        {
            command.ExecuteNonQuery();
        }

        ResetIdentitySequence(connection, "public.survey", "id_survey");

        if (TableExists(connection, "history_survey_question"))
        {
            using var command = new NpgsqlCommand(
                """
                INSERT INTO public.survey_question (id_survey, question_order, question_text)
                SELECT
                    id_survey,
                    question_order,
                    question_text
                FROM public.history_survey_question
                ON CONFLICT (id_survey, question_order) DO UPDATE
                SET question_text = EXCLUDED.question_text;
                """,
                connection);

            command.ExecuteNonQuery();
        }
    }

    private static void BackfillSurveyQuestions(NpgsqlConnection connection)
    {
        if (!LegacyColumnExists(connection, "survey", "questions"))
        {
            return;
        }

        using var command = new NpgsqlCommand(
            """
            INSERT INTO public.survey_question (id_survey, question_order, question_text)
            SELECT
                s.id_survey,
                CASE
                    WHEN COALESCE(question.item ->> 'question_id', '') ~ '^[0-9]+$'
                        THEN (question.item ->> 'question_id')::integer
                    ELSE question.ordinality::integer
                END AS question_order,
                COALESCE(
                    NULLIF(BTRIM(question.item ->> 'text'), ''),
                    'Вопрос ' || question.ordinality::text
                ) AS question_text
            FROM public.survey s
            CROSS JOIN LATERAL jsonb_array_elements(
                CASE
                    WHEN jsonb_typeof(s.questions -> 'questions') = 'array' THEN s.questions -> 'questions'
                    WHEN jsonb_typeof(s.questions) = 'array' THEN s.questions
                    ELSE '[]'::jsonb
                END
            ) WITH ORDINALITY AS question(item, ordinality)
            ON CONFLICT (id_survey, question_order) DO UPDATE
            SET question_text = EXCLUDED.question_text;
            """,
            connection);

        command.ExecuteNonQuery();
    }

    private static void BackfillArchivedSurveyQuestions(NpgsqlConnection connection)
    {
        if (!LegacyColumnExists(connection, "history_survey", "file_questions"))
        {
            return;
        }

        using var command = new NpgsqlCommand(
            """
            INSERT INTO public.survey_question (id_survey, question_order, question_text)
            SELECT
                hs.id_survey,
                CASE
                    WHEN COALESCE(question.item ->> 'question_id', '') ~ '^[0-9]+$'
                        THEN (question.item ->> 'question_id')::integer
                    ELSE question.ordinality::integer
                END AS question_order,
                COALESCE(
                    NULLIF(BTRIM(question.item ->> 'text'), ''),
                    'Вопрос ' || question.ordinality::text
                ) AS question_text
            FROM public.history_survey hs
            CROSS JOIN LATERAL jsonb_array_elements(
                CASE
                    WHEN jsonb_typeof(hs.file_questions -> 'questions') = 'array' THEN hs.file_questions -> 'questions'
                    WHEN jsonb_typeof(hs.file_questions) = 'array' THEN hs.file_questions
                    ELSE '[]'::jsonb
                END
            ) WITH ORDINALITY AS question(item, ordinality)
            ON CONFLICT (id_survey, question_order) DO UPDATE
            SET question_text = EXCLUDED.question_text;
            """,
            connection);

        command.ExecuteNonQuery();
    }

    private static void BackfillAnswerItems(NpgsqlConnection connection)
    {
        if (!LegacyColumnExists(connection, "answer", "answers"))
        {
            return;
        }

        using var command = new NpgsqlCommand(
            """
            INSERT INTO public.answer_item (id_answer, question_order, question_text, rating, comment)
            SELECT
                a.id_answer,
                CASE
                    WHEN COALESCE(answer_row.item ->> 'question_id', '') ~ '^[0-9]+$'
                        THEN (answer_row.item ->> 'question_id')::integer
                    ELSE answer_row.ordinality::integer
                END AS question_order,
                COALESCE(
                    NULLIF(BTRIM(COALESCE(answer_row.item ->> 'question_text', answer_row.item ->> 'text')), ''),
                    'Вопрос ' || answer_row.ordinality::text
                ) AS question_text,
                CASE
                    WHEN COALESCE(answer_row.item ->> 'rating', '') ~ '^[0-9]+$'
                        THEN (answer_row.item ->> 'rating')::integer
                    ELSE NULL
                END AS rating,
                NULLIF(answer_row.item ->> 'comment', '') AS comment
            FROM public.answer a
            CROSS JOIN LATERAL jsonb_array_elements(
                CASE
                    WHEN jsonb_typeof(a.answers) = 'array' THEN a.answers
                    ELSE '[]'::jsonb
                END
            ) WITH ORDINALITY AS answer_row(item, ordinality)
            ON CONFLICT (id_answer, question_order) DO UPDATE
            SET question_text = EXCLUDED.question_text,
                rating = EXCLUDED.rating,
                comment = EXCLUDED.comment;
            """,
            connection);

        command.ExecuteNonQuery();
    }

    private static void MigrateExtensions(NpgsqlConnection connection)
    {
        if (!TableExists(connection, "access_extension"))
        {
            return;
        }

        using var command = new NpgsqlCommand(
            """
            INSERT INTO public.organization_survey (organization_id, id_survey, extended_until)
            SELECT
                organization_id,
                id_survey,
                MAX(new_end_date) AS extended_until
            FROM public.access_extension
            GROUP BY organization_id, id_survey
            ON CONFLICT (organization_id, id_survey) DO UPDATE
            SET extended_until = CASE
                WHEN public.organization_survey.extended_until IS NULL THEN EXCLUDED.extended_until
                ELSE GREATEST(public.organization_survey.extended_until, EXCLUDED.extended_until)
            END;
            """,
            connection);

        command.ExecuteNonQuery();
    }

    private static void DropLegacyColumns(NpgsqlConnection connection)
    {
        using var command = new NpgsqlCommand(
            """
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = 'public'
                      AND table_name = 'survey'
                      AND column_name = 'questions'
                ) THEN
                    ALTER TABLE public.survey DROP COLUMN questions;
                END IF;

                IF EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = 'public'
                      AND table_name = 'answer'
                      AND column_name = 'answers'
                ) THEN
                    ALTER TABLE public.answer DROP COLUMN answers;
                END IF;

                IF EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = 'public'
                      AND table_name = 'history_survey'
                      AND column_name = 'file_questions'
                ) THEN
                    ALTER TABLE public.history_survey DROP COLUMN file_questions;
                END IF;
            END $$;
            """,
            connection);

        command.ExecuteNonQuery();
    }

    private static void DropLegacyTables(NpgsqlConnection connection)
    {
        using var command = new NpgsqlCommand(
            """
            DO $$
            BEGIN
                IF to_regclass('public.history_survey_question') IS NOT NULL THEN
                    DROP TABLE public.history_survey_question;
                END IF;

                IF to_regclass('public.history_survey') IS NOT NULL THEN
                    DROP TABLE public.history_survey;
                END IF;

                IF to_regclass('public.access_extension') IS NOT NULL THEN
                    DROP TABLE public.access_extension;
                END IF;
            END $$;
            """,
            connection);

        command.ExecuteNonQuery();
    }

    private static bool TableExists(NpgsqlConnection connection, string tableName)
    {
        using var command = new NpgsqlCommand(
            """
            SELECT EXISTS (
                SELECT 1
                FROM information_schema.tables
                WHERE table_schema = 'public'
                  AND table_name = @tableName
            );
            """,
            connection);

        command.Parameters.AddWithValue("@tableName", tableName);
        return command.ExecuteScalar() is bool exists && exists;
    }

    private static bool LegacyColumnExists(NpgsqlConnection connection, string tableName, string columnName)
    {
        using var command = new NpgsqlCommand(
            """
            SELECT EXISTS (
                SELECT 1
                FROM information_schema.columns
                WHERE table_schema = 'public'
                  AND table_name = @tableName
                  AND column_name = @columnName
            );
            """,
            connection);

        command.Parameters.AddWithValue("@tableName", tableName);
        command.Parameters.AddWithValue("@columnName", columnName);
        return command.ExecuteScalar() is bool exists && exists;
    }

    private static void ResetIdentitySequence(NpgsqlConnection connection, string tableName, string columnName)
    {
        var (schemaName, relationName) = SplitQualifiedName(tableName);
        using var command = new NpgsqlCommand(
            $"""
            SELECT setval(
                pg_get_serial_sequence('{schemaName}.{relationName}', '{columnName}'),
                COALESCE((SELECT MAX({QuoteIdentifier(columnName)}) FROM {QuoteQualifiedName(schemaName, relationName)}), 1),
                true
            );
            """,
            connection);

        command.ExecuteNonQuery();
    }

    private static (string SchemaName, string ObjectName) SplitQualifiedName(string qualifiedName)
    {
        var parts = qualifiedName.Split('.', 2, StringSplitOptions.TrimEntries);
        if (parts.Length != 2 || string.IsNullOrWhiteSpace(parts[0]) || string.IsNullOrWhiteSpace(parts[1]))
        {
            throw new ArgumentException($"Expected a schema-qualified name, got '{qualifiedName}'.", nameof(qualifiedName));
        }

        return (parts[0], parts[1]);
    }

    private static string QuoteQualifiedName(string schemaName, string objectName)
    {
        return $"{QuoteIdentifier(schemaName)}.{QuoteIdentifier(objectName)}";
    }

    private static string QuoteIdentifier(string identifier)
    {
        return $"\"{identifier.Replace("\"", "\"\"")}\"";
    }
}
