using Npgsql;

namespace main_project.Infrastructure.Database;

public static class SurveyNormalizationBootstrapper
{
    private static readonly object SyncRoot = new();
    private static bool _initialized;

    public static void EnsureInitialized(NpgsqlConnection connection)
    {
        if (_initialized)
        {
            return;
        }

        lock (SyncRoot)
        {
            if (_initialized)
            {
                return;
            }

            using var command = new NpgsqlCommand(
                """
                CREATE TABLE IF NOT EXISTS public.survey_questions (
                    id_question integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    id_survey integer NOT NULL,
                    question_order integer NOT NULL,
                    question_text text NOT NULL,
                    created_at timestamp without time zone NOT NULL DEFAULT NOW(),
                    CONSTRAINT fk_survey_questions_survey
                        FOREIGN KEY (id_survey) REFERENCES public.surveys (id_survey) ON DELETE CASCADE,
                    CONSTRAINT uq_survey_questions_order
                        UNIQUE (id_survey, question_order)
                );

                CREATE TABLE IF NOT EXISTS public.history_answer_items (
                    id_item integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    id_answer integer NOT NULL,
                    question_order integer NOT NULL,
                    question_text text NOT NULL,
                    rating integer,
                    comment text,
                    CONSTRAINT fk_history_answer_items_answer
                        FOREIGN KEY (id_answer) REFERENCES public.history_answer (id_answer) ON DELETE CASCADE,
                    CONSTRAINT uq_history_answer_items_order
                        UNIQUE (id_answer, question_order),
                    CONSTRAINT chk_history_answer_items_rating
                        CHECK (rating IS NULL OR (rating >= 1 AND rating <= 5))
                );

                CREATE TABLE IF NOT EXISTS public.history_survey_questions (
                    id_history_question integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    id_survey integer NOT NULL,
                    question_order integer NOT NULL,
                    question_text text NOT NULL,
                    created_at timestamp without time zone NOT NULL DEFAULT NOW(),
                    CONSTRAINT uq_history_survey_questions_order
                        UNIQUE (id_survey, question_order)
                );

                CREATE INDEX IF NOT EXISTS idx_survey_questions_id_survey
                    ON public.survey_questions (id_survey, question_order);

                CREATE INDEX IF NOT EXISTS idx_history_answer_items_id_answer
                    ON public.history_answer_items (id_answer, question_order);

                CREATE INDEX IF NOT EXISTS idx_history_survey_questions_id_survey
                    ON public.history_survey_questions (id_survey, question_order);
                """,
                connection);

            command.ExecuteNonQuery();

            BackfillSurveyQuestions(connection);
            BackfillHistorySurveyQuestions(connection);
            BackfillHistoryAnswerItems(connection);
            DropLegacyColumns(connection);

            _initialized = true;
        }
    }

    private static void BackfillSurveyQuestions(NpgsqlConnection connection)
    {
        if (!LegacyColumnExists(connection, "surveys", "questions"))
        {
            return;
        }

        using var command = new NpgsqlCommand(
            """
            INSERT INTO public.survey_questions (id_survey, question_order, question_text)
            SELECT
                s.id_survey,
                CASE
                    WHEN COALESCE(question.item ->> 'question_id', '') ~ '^[0-9]+$'
                        THEN (question.item ->> 'question_id')::integer
                    ELSE question.ordinality::integer
                END AS question_order,
                COALESCE(
                    NULLIF(BTRIM(question.item ->> 'text'), ''),
                    'Вопрос ' || question.ordinality::text
                ) AS question_text
            FROM public.surveys s
            CROSS JOIN LATERAL jsonb_array_elements(
                CASE
                    WHEN jsonb_typeof(s.questions -> 'questions') = 'array' THEN s.questions -> 'questions'
                    WHEN jsonb_typeof(s.questions) = 'array' THEN s.questions
                    ELSE '[]'::jsonb
                END
            ) WITH ORDINALITY AS question(item, ordinality)
            ON CONFLICT (id_survey, question_order) DO UPDATE
            SET question_text = EXCLUDED.question_text;
            """,
            connection);

        command.ExecuteNonQuery();
    }

    private static void BackfillHistoryAnswerItems(NpgsqlConnection connection)
    {
        if (!LegacyColumnExists(connection, "history_answer", "answers"))
        {
            return;
        }

        using var command = new NpgsqlCommand(
            """
            INSERT INTO public.history_answer_items (id_answer, question_order, question_text, rating, comment)
            SELECT
                ha.id_answer,
                CASE
                    WHEN COALESCE(answer_item.item ->> 'question_id', '') ~ '^[0-9]+$'
                        THEN (answer_item.item ->> 'question_id')::integer
                    ELSE answer_item.ordinality::integer
                END AS question_order,
                COALESCE(
                    NULLIF(BTRIM(COALESCE(answer_item.item ->> 'question_text', answer_item.item ->> 'text')), ''),
                    'Вопрос ' || answer_item.ordinality::text
                ) AS question_text,
                CASE
                    WHEN COALESCE(answer_item.item ->> 'rating', '') ~ '^[0-9]+$'
                        THEN (answer_item.item ->> 'rating')::integer
                    ELSE NULL
                END AS rating,
                NULLIF(answer_item.item ->> 'comment', '') AS comment
            FROM public.history_answer ha
            CROSS JOIN LATERAL jsonb_array_elements(
                CASE
                    WHEN jsonb_typeof(ha.answers) = 'array' THEN ha.answers
                    ELSE '[]'::jsonb
                END
            ) WITH ORDINALITY AS answer_item(item, ordinality)
            ON CONFLICT (id_answer, question_order) DO UPDATE
            SET question_text = EXCLUDED.question_text,
                rating = EXCLUDED.rating,
                comment = EXCLUDED.comment;
            """,
            connection);

        command.ExecuteNonQuery();
    }

    private static void BackfillHistorySurveyQuestions(NpgsqlConnection connection)
    {
        using var command = new NpgsqlCommand(
            """
            INSERT INTO public.history_survey_questions (id_survey, question_order, question_text)
            SELECT
                hs.id_survey,
                CASE
                    WHEN COALESCE(question.item ->> 'question_id', '') ~ '^[0-9]+$'
                        THEN (question.item ->> 'question_id')::integer
                    ELSE question.ordinality::integer
                END AS question_order,
                COALESCE(
                    NULLIF(BTRIM(question.item ->> 'text'), ''),
                    'Вопрос ' || question.ordinality::text
                ) AS question_text
            FROM public.history_surveys hs
            CROSS JOIN LATERAL jsonb_array_elements(
                CASE
                    WHEN jsonb_typeof(hs.file_questions -> 'questions') = 'array' THEN hs.file_questions -> 'questions'
                    WHEN jsonb_typeof(hs.file_questions) = 'array' THEN hs.file_questions
                    ELSE '[]'::jsonb
                END
            ) WITH ORDINALITY AS question(item, ordinality)
            ON CONFLICT (id_survey, question_order) DO UPDATE
            SET question_text = EXCLUDED.question_text;
            """,
            connection);

        if (LegacyColumnExists(connection, "history_surveys", "file_questions"))
        {
            command.ExecuteNonQuery();
        }
    }

    private static void DropLegacyColumns(NpgsqlConnection connection)
    {
        using var command = new NpgsqlCommand(
            """
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = 'public'
                      AND table_name = 'surveys'
                      AND column_name = 'questions'
                ) THEN
                    ALTER TABLE public.surveys DROP COLUMN questions;
                END IF;

                IF EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = 'public'
                      AND table_name = 'history_surveys'
                      AND column_name = 'file_questions'
                ) THEN
                    ALTER TABLE public.history_surveys DROP COLUMN file_questions;
                END IF;

                IF EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = 'public'
                      AND table_name = 'history_answer'
                      AND column_name = 'answers'
                ) THEN
                    ALTER TABLE public.history_answer DROP COLUMN answers;
                END IF;
            END $$;
            """,
            connection);

        command.ExecuteNonQuery();
    }

    private static bool LegacyColumnExists(NpgsqlConnection connection, string tableName, string columnName)
    {
        using var command = new NpgsqlCommand(
            """
            SELECT EXISTS (
                SELECT 1
                FROM information_schema.columns
                WHERE table_schema = 'public'
                  AND table_name = @tableName
                  AND column_name = @columnName
            );
            """,
            connection);

        command.Parameters.AddWithValue("@tableName", tableName);
        command.Parameters.AddWithValue("@columnName", columnName);
        return command.ExecuteScalar() is bool exists && exists;
    }
}
